
package views;

import com.formdev.flatlaf.FlatLightLaf;


/**
 *
 * @author Vilberto Patricio
 */

public class CrearEjercicio extends javax.swing.JPanel {

    public CrearEjercicio() {
        initComponents();
        FlatLightLaf.setup(); //Modifica el diseño de los componentes de las interfaces graficas
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgCrearGrupo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelBreadCrumbsCrearGrupo = new javax.swing.JLabel();
        btnCrearGrupo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanelContenedorCrearEjercicio = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgCrearGrupo.setBackground(new java.awt.Color(241, 243, 246));
        bgCrearGrupo.setPreferredSize(new java.awt.Dimension(1260, 850));
        bgCrearGrupo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(253, 116, 1));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Creación de ejercicios");
        bgCrearGrupo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 500, -1));

        jLabelBreadCrumbsCrearGrupo.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabelBreadCrumbsCrearGrupo.setText("Juez Cachimbo / Seguimiento / Crear ejercicio");
        bgCrearGrupo.add(jLabelBreadCrumbsCrearGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        btnCrearGrupo.setBackground(new java.awt.Color(253, 116, 1));
        btnCrearGrupo.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        btnCrearGrupo.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearGrupo.setText("Siguiente");
        bgCrearGrupo.add(btnCrearGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 850, 180, 40));

        btnCancelar.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(253, 116, 1));
        btnCancelar.setText("Regresar");
        bgCrearGrupo.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 850, 170, 40));

        jPanelContenedorCrearEjercicio.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(242, 227, 216), new java.awt.Color(242, 227, 216)));
        bgCrearGrupo.add(jPanelContenedorCrearEjercicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 1030, 650));

        add(bgCrearGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 953));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgCrearGrupo;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnCrearGrupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBreadCrumbsCrearGrupo;
    public javax.swing.JPanel jPanelContenedorCrearEjercicio;
    // End of variables declaration//GEN-END:variables
}
