/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import com.formdev.flatlaf.FlatLightLaf;

/**
 *
 * @author Usuario
 */
public class EdicionDatosPersonales extends javax.swing.JFrame {

    /**
     * Creates new form EdicionDatosPersonales
     */
    public EdicionDatosPersonales() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEdicionDatos = new javax.swing.JPanel();
        labelTituloEdicion = new javax.swing.JLabel();
        labelNombreED = new javax.swing.JLabel();
        txtPasswordED = new javax.swing.JTextField();
        labelApellidosED = new javax.swing.JLabel();
        labelUsernameED = new javax.swing.JLabel();
        labelPasswordED = new javax.swing.JLabel();
        btnGuardarED = new javax.swing.JButton();
        btnCancelarED = new javax.swing.JButton();
        txtNombreED = new javax.swing.JTextField();
        txtApellidosED = new javax.swing.JTextField();
        txtUsernameED = new javax.swing.JTextField();
        labelBreadCrumbMDP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelEdicionDatos.setBackground(new java.awt.Color(255, 255, 255));
        jPanelEdicionDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTituloEdicion.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        labelTituloEdicion.setForeground(new java.awt.Color(30, 39, 114));
        labelTituloEdicion.setText("Edición de datos personales");
        jPanelEdicionDatos.add(labelTituloEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        labelNombreED.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        labelNombreED.setForeground(new java.awt.Color(85, 85, 85));
        labelNombreED.setText("Nombre");
        jPanelEdicionDatos.add(labelNombreED, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        txtPasswordED.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtPasswordED.setForeground(new java.awt.Color(85, 85, 85));
        jPanelEdicionDatos.add(txtPasswordED, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, 390, 40));

        labelApellidosED.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        labelApellidosED.setForeground(new java.awt.Color(85, 85, 85));
        labelApellidosED.setText("Apellidos");
        jPanelEdicionDatos.add(labelApellidosED, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        labelUsernameED.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        labelUsernameED.setForeground(new java.awt.Color(85, 85, 85));
        labelUsernameED.setText("Nombre de usuario");
        jPanelEdicionDatos.add(labelUsernameED, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        labelPasswordED.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        labelPasswordED.setForeground(new java.awt.Color(85, 85, 85));
        labelPasswordED.setText("Contraseña");
        jPanelEdicionDatos.add(labelPasswordED, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, -1, -1));

        btnGuardarED.setBackground(new java.awt.Color(253, 116, 1));
        btnGuardarED.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        btnGuardarED.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarED.setText("Guardar");
        btnGuardarED.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarED.setFocusable(false);
        btnGuardarED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEDActionPerformed(evt);
            }
        });
        jPanelEdicionDatos.add(btnGuardarED, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 690, 180, 40));

        btnCancelarED.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        btnCancelarED.setForeground(new java.awt.Color(253, 116, 1));
        btnCancelarED.setText("Cancelar");
        btnCancelarED.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarED.setFocusable(false);
        btnCancelarED.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarEDMouseEntered(evt);
            }
        });
        jPanelEdicionDatos.add(btnCancelarED, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 690, 160, 40));

        txtNombreED.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtNombreED.setForeground(new java.awt.Color(85, 85, 85));
        jPanelEdicionDatos.add(txtNombreED, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 390, 40));

        txtApellidosED.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtApellidosED.setForeground(new java.awt.Color(85, 85, 85));
        jPanelEdicionDatos.add(txtApellidosED, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 390, 40));

        txtUsernameED.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtUsernameED.setForeground(new java.awt.Color(85, 85, 85));
        jPanelEdicionDatos.add(txtUsernameED, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 390, 40));

        labelBreadCrumbMDP.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        labelBreadCrumbMDP.setText("Juez Cachimbo / Perfil / Modificación de datos personales");
        jPanelEdicionDatos.add(labelBreadCrumbMDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelEdicionDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelEdicionDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarEDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarEDMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarEDMouseEntered

    private void btnGuardarEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarEDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EdicionDatosPersonales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EdicionDatosPersonales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EdicionDatosPersonales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EdicionDatosPersonales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatLightLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EdicionDatosPersonales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelarED;
    public javax.swing.JButton btnGuardarED;
    private javax.swing.JPanel jPanelEdicionDatos;
    private javax.swing.JLabel labelApellidosED;
    private javax.swing.JLabel labelBreadCrumbMDP;
    private javax.swing.JLabel labelNombreED;
    private javax.swing.JLabel labelPasswordED;
    private javax.swing.JLabel labelTituloEdicion;
    private javax.swing.JLabel labelUsernameED;
    public javax.swing.JTextField txtApellidosED;
    public javax.swing.JTextField txtNombreED;
    public javax.swing.JTextField txtPasswordED;
    public javax.swing.JTextField txtUsernameED;
    // End of variables declaration//GEN-END:variables
}
