/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import com.formdev.flatlaf.FlatLightLaf;

/**
 *
 * @author Usuario
 */
public class EdicionDatosEstudiante extends javax.swing.JFrame {

    /**
     * Creates new form EdicionDatosPersonales
     */
    public EdicionDatosEstudiante() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEdicionDatos = new javax.swing.JPanel();
        labelTituloEdicion = new javax.swing.JLabel();
        labelNombreED = new javax.swing.JLabel();
        txtPasswordEdicionEstudiante = new javax.swing.JTextField();
        labelApellidosED = new javax.swing.JLabel();
        labelUsernameED = new javax.swing.JLabel();
        labelPasswordED = new javax.swing.JLabel();
        btnGuardarEdicionEstudiante = new javax.swing.JButton();
        btnCancelarEdicionEstudiante = new javax.swing.JButton();
        txtNombreEdicionEstudiante = new javax.swing.JTextField();
        txtApellidosEdicionEstudiante = new javax.swing.JTextField();
        txtUsernameEdicionEstudiante = new javax.swing.JTextField();
        labelBreadCrumbMDP = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelEdicionDatos.setBackground(new java.awt.Color(255, 255, 255));
        jPanelEdicionDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTituloEdicion.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        labelTituloEdicion.setForeground(new java.awt.Color(30, 39, 114));
        labelTituloEdicion.setText("Edición de datos personales");
        jPanelEdicionDatos.add(labelTituloEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        labelNombreED.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        labelNombreED.setForeground(new java.awt.Color(85, 85, 85));
        labelNombreED.setText("Nombre");
        jPanelEdicionDatos.add(labelNombreED, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        txtPasswordEdicionEstudiante.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtPasswordEdicionEstudiante.setForeground(new java.awt.Color(85, 85, 85));
        jPanelEdicionDatos.add(txtPasswordEdicionEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 600, 390, 40));

        labelApellidosED.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        labelApellidosED.setForeground(new java.awt.Color(85, 85, 85));
        labelApellidosED.setText("Apellidos");
        jPanelEdicionDatos.add(labelApellidosED, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        labelUsernameED.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        labelUsernameED.setForeground(new java.awt.Color(85, 85, 85));
        labelUsernameED.setText("Nombre de usuario");
        jPanelEdicionDatos.add(labelUsernameED, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, -1));

        labelPasswordED.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        labelPasswordED.setForeground(new java.awt.Color(85, 85, 85));
        labelPasswordED.setText("Contraseña");
        jPanelEdicionDatos.add(labelPasswordED, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, -1, -1));

        btnGuardarEdicionEstudiante.setBackground(new java.awt.Color(253, 116, 1));
        btnGuardarEdicionEstudiante.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        btnGuardarEdicionEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarEdicionEstudiante.setText("Guardar");
        btnGuardarEdicionEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarEdicionEstudiante.setFocusable(false);
        btnGuardarEdicionEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEdicionEstudianteActionPerformed(evt);
            }
        });
        jPanelEdicionDatos.add(btnGuardarEdicionEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 700, 180, 40));

        btnCancelarEdicionEstudiante.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        btnCancelarEdicionEstudiante.setForeground(new java.awt.Color(253, 116, 1));
        btnCancelarEdicionEstudiante.setText("Cancelar");
        btnCancelarEdicionEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarEdicionEstudiante.setFocusable(false);
        btnCancelarEdicionEstudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarEdicionEstudianteMouseEntered(evt);
            }
        });
        jPanelEdicionDatos.add(btnCancelarEdicionEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 700, 160, 40));

        txtNombreEdicionEstudiante.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtNombreEdicionEstudiante.setForeground(new java.awt.Color(85, 85, 85));
        jPanelEdicionDatos.add(txtNombreEdicionEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 390, 40));

        txtApellidosEdicionEstudiante.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtApellidosEdicionEstudiante.setForeground(new java.awt.Color(85, 85, 85));
        jPanelEdicionDatos.add(txtApellidosEdicionEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 390, 40));

        txtUsernameEdicionEstudiante.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtUsernameEdicionEstudiante.setForeground(new java.awt.Color(85, 85, 85));
        jPanelEdicionDatos.add(txtUsernameEdicionEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 390, 40));

        labelBreadCrumbMDP.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        labelBreadCrumbMDP.setText("Juez Cachimbo / Perfil / Modificación de datos personales");
        jPanelEdicionDatos.add(labelBreadCrumbMDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 0, 16)); // NOI18N
        jLabel1.setText("Estudiante");
        jPanelEdicionDatos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelEdicionDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelEdicionDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarEdicionEstudianteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarEdicionEstudianteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarEdicionEstudianteMouseEntered

    private void btnGuardarEdicionEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEdicionEstudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarEdicionEstudianteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EdicionDatosEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EdicionDatosEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EdicionDatosEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EdicionDatosEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatLightLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EdicionDatosEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelarEdicionEstudiante;
    public javax.swing.JButton btnGuardarEdicionEstudiante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelEdicionDatos;
    private javax.swing.JLabel labelApellidosED;
    private javax.swing.JLabel labelBreadCrumbMDP;
    private javax.swing.JLabel labelNombreED;
    private javax.swing.JLabel labelPasswordED;
    private javax.swing.JLabel labelTituloEdicion;
    private javax.swing.JLabel labelUsernameED;
    public javax.swing.JTextField txtApellidosEdicionEstudiante;
    public javax.swing.JTextField txtNombreEdicionEstudiante;
    public javax.swing.JTextField txtPasswordEdicionEstudiante;
    public javax.swing.JTextField txtUsernameEdicionEstudiante;
    // End of variables declaration//GEN-END:variables
}
