/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import com.formdev.flatlaf.FlatLightLaf;

/**
 *
 * @author Usuario
 */
public class EdicionDatosDocente extends javax.swing.JFrame {

    /**
     * Creates new form EdicionDatosPersonales
     */
    public EdicionDatosDocente() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEdicionDatos = new javax.swing.JPanel();
        labelTituloEdicion = new javax.swing.JLabel();
        labelNombreED = new javax.swing.JLabel();
        txtPasswordEdicionDocente = new javax.swing.JTextField();
        labelApellidosED = new javax.swing.JLabel();
        labelUsernameED = new javax.swing.JLabel();
        labelPasswordED = new javax.swing.JLabel();
        btnGuardarEdicionDocente = new javax.swing.JButton();
        btnCancelarEdicionDocente = new javax.swing.JButton();
        txtNombreEdicionEstudiante = new javax.swing.JTextField();
        txtApellidosEdicionDocente = new javax.swing.JTextField();
        txtUsernameEdicionDocente = new javax.swing.JTextField();
        labelBreadCrumbMDP = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCarreraProfesionalEdicionDocente = new javax.swing.JTextField();
        labelApellidosED1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelEdicionDatos.setBackground(new java.awt.Color(255, 255, 255));
        jPanelEdicionDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTituloEdicion.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        labelTituloEdicion.setForeground(new java.awt.Color(30, 39, 114));
        labelTituloEdicion.setText("Edición de datos personales");
        jPanelEdicionDatos.add(labelTituloEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        labelNombreED.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        labelNombreED.setForeground(new java.awt.Color(85, 85, 85));
        labelNombreED.setText("Nombre");
        jPanelEdicionDatos.add(labelNombreED, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        txtPasswordEdicionDocente.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtPasswordEdicionDocente.setForeground(new java.awt.Color(85, 85, 85));
        jPanelEdicionDatos.add(txtPasswordEdicionDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, 390, 40));

        labelApellidosED.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        labelApellidosED.setForeground(new java.awt.Color(85, 85, 85));
        labelApellidosED.setText("Apellidos");
        jPanelEdicionDatos.add(labelApellidosED, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        labelUsernameED.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        labelUsernameED.setForeground(new java.awt.Color(85, 85, 85));
        labelUsernameED.setText("Nombre de usuario");
        jPanelEdicionDatos.add(labelUsernameED, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, -1, -1));

        labelPasswordED.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        labelPasswordED.setForeground(new java.awt.Color(85, 85, 85));
        labelPasswordED.setText("Contraseña");
        jPanelEdicionDatos.add(labelPasswordED, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, -1, -1));

        btnGuardarEdicionDocente.setBackground(new java.awt.Color(253, 116, 1));
        btnGuardarEdicionDocente.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        btnGuardarEdicionDocente.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarEdicionDocente.setText("Guardar");
        btnGuardarEdicionDocente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarEdicionDocente.setFocusable(false);
        btnGuardarEdicionDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEdicionDocenteActionPerformed(evt);
            }
        });
        jPanelEdicionDatos.add(btnGuardarEdicionDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 700, 180, 40));

        btnCancelarEdicionDocente.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        btnCancelarEdicionDocente.setForeground(new java.awt.Color(253, 116, 1));
        btnCancelarEdicionDocente.setText("Cancelar");
        btnCancelarEdicionDocente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarEdicionDocente.setFocusable(false);
        btnCancelarEdicionDocente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarEdicionDocenteMouseEntered(evt);
            }
        });
        jPanelEdicionDatos.add(btnCancelarEdicionDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 700, 160, 40));

        txtNombreEdicionEstudiante.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtNombreEdicionEstudiante.setForeground(new java.awt.Color(85, 85, 85));
        jPanelEdicionDatos.add(txtNombreEdicionEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 390, 40));

        txtApellidosEdicionDocente.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtApellidosEdicionDocente.setForeground(new java.awt.Color(85, 85, 85));
        jPanelEdicionDatos.add(txtApellidosEdicionDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 390, 40));

        txtUsernameEdicionDocente.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtUsernameEdicionDocente.setForeground(new java.awt.Color(85, 85, 85));
        jPanelEdicionDatos.add(txtUsernameEdicionDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 390, 40));

        labelBreadCrumbMDP.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        labelBreadCrumbMDP.setText("Juez Cachimbo / Perfil / Modificación de datos personales");
        jPanelEdicionDatos.add(labelBreadCrumbMDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 0, 16)); // NOI18N
        jLabel1.setText("Docente");
        jPanelEdicionDatos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        txtCarreraProfesionalEdicionDocente.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtCarreraProfesionalEdicionDocente.setForeground(new java.awt.Color(85, 85, 85));
        jPanelEdicionDatos.add(txtCarreraProfesionalEdicionDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 390, 40));

        labelApellidosED1.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        labelApellidosED1.setForeground(new java.awt.Color(85, 85, 85));
        labelApellidosED1.setText("Carrera profesional");
        jPanelEdicionDatos.add(labelApellidosED1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelEdicionDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelEdicionDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarEdicionDocenteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarEdicionDocenteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarEdicionDocenteMouseEntered

    private void btnGuardarEdicionDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEdicionDocenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarEdicionDocenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EdicionDatosDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EdicionDatosDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EdicionDatosDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EdicionDatosDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatLightLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EdicionDatosDocente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelarEdicionDocente;
    public javax.swing.JButton btnGuardarEdicionDocente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelEdicionDatos;
    private javax.swing.JLabel labelApellidosED;
    private javax.swing.JLabel labelApellidosED1;
    private javax.swing.JLabel labelBreadCrumbMDP;
    private javax.swing.JLabel labelNombreED;
    private javax.swing.JLabel labelPasswordED;
    private javax.swing.JLabel labelTituloEdicion;
    private javax.swing.JLabel labelUsernameED;
    public javax.swing.JTextField txtApellidosEdicionDocente;
    public javax.swing.JTextField txtCarreraProfesionalEdicionDocente;
    public javax.swing.JTextField txtNombreEdicionEstudiante;
    public javax.swing.JTextField txtPasswordEdicionDocente;
    public javax.swing.JTextField txtUsernameEdicionDocente;
    // End of variables declaration//GEN-END:variables
}
