
package views;

import com.formdev.flatlaf.FlatLightLaf;


/**
 *
 * @author Vilberto Patricio
 */

public class EstadisticasDocente1 extends javax.swing.JPanel {

    public EstadisticasDocente1() {
        initComponents();
        FlatLightLaf.setup(); //Modifica el diseño de los componentes de las interfaces graficas
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgInicioDocente = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        bgPerfilDocente = new javax.swing.JPanel();
        jLabelBreadCrumbsPerfilD = new javax.swing.JLabel();
        jPanelFotoPerfilD = new javax.swing.JPanel();
        jLabelCarreraPD = new javax.swing.JLabel();
        jScrollPaneEstadisticasD = new javax.swing.JScrollPane();
        jPanelScrollBarEstadisticas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelTextosCreados = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelNumTxtCreados = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelTxtPreguntasCorrectas = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelTxtPreguntasIncorrectas = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanelPreguntasRespondidas = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabelPreguntasEstudiantes = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelPreguntasAcertadasEstudiantes = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelPreguntasNoAcertadas = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelPorcentajePreguntasAcertadas = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabelPorcentajePreguntasNoAcertadas = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPaneOtrasEstadisticas = new javax.swing.JScrollPane();
        jTableOtrasEstadisticas = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jScrollPaneTextosMasLeidos = new javax.swing.JScrollPane();
        jTableTextosMasLeidos = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgInicioDocente.setBackground(new java.awt.Color(241, 243, 246));
        bgInicioDocente.setPreferredSize(new java.awt.Dimension(1260, 850));
        bgInicioDocente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgPerfilDocente.setBackground(new java.awt.Color(241, 243, 246));
        bgPerfilDocente.setPreferredSize(new java.awt.Dimension(1260, 850));
        bgPerfilDocente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelBreadCrumbsPerfilD.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabelBreadCrumbsPerfilD.setText("Juez Cachimbo / Estadísticas generales");
        bgPerfilDocente.add(jLabelBreadCrumbsPerfilD, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanelFotoPerfilD.setBackground(new java.awt.Color(241, 243, 246));
        jPanelFotoPerfilD.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(243, 213, 190), new java.awt.Color(243, 213, 190)));

        javax.swing.GroupLayout jPanelFotoPerfilDLayout = new javax.swing.GroupLayout(jPanelFotoPerfilD);
        jPanelFotoPerfilD.setLayout(jPanelFotoPerfilDLayout);
        jPanelFotoPerfilDLayout.setHorizontalGroup(
            jPanelFotoPerfilDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );
        jPanelFotoPerfilDLayout.setVerticalGroup(
            jPanelFotoPerfilDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );

        bgPerfilDocente.add(jPanelFotoPerfilD, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 100, 100));

        jLabelCarreraPD.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabelCarreraPD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCarreraPD.setText("{Username}");
        bgPerfilDocente.add(jLabelCarreraPD, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 100, -1));

        jScrollPaneEstadisticasD.setBackground(new java.awt.Color(241, 243, 246));
        jScrollPaneEstadisticasD.setBorder(null);
        jScrollPaneEstadisticasD.setFocusable(false);

        jPanelScrollBarEstadisticas.setBackground(new java.awt.Color(241, 243, 246));
        jPanelScrollBarEstadisticas.setFocusable(false);
        jPanelScrollBarEstadisticas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(253, 116, 1));
        jLabel1.setText("Preguntas respondidas");
        jPanelScrollBarEstadisticas.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        jPanelTextosCreados.setBackground(new java.awt.Color(241, 243, 246));
        jPanelTextosCreados.setLayout(new java.awt.GridLayout(3, 2, 4, 4));

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel2.setText("Cantidad de textos creados:");
        jPanelTextosCreados.add(jLabel2);

        jLabelNumTxtCreados.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabelNumTxtCreados.setText("50");
        jPanelTextosCreados.add(jLabelNumTxtCreados);

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("<html>Cantidad de textos en los que se respondió correctamente todas las preguntas:</html>");
        jPanelTextosCreados.add(jLabel3);

        jLabelTxtPreguntasCorrectas.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabelTxtPreguntasCorrectas.setText("10");
        jPanelTextosCreados.add(jLabelTxtPreguntasCorrectas);

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel6.setText("<html>Cantidad de textos en los que se respondió incorrectamenta todas las preguntas:</html>");
        jPanelTextosCreados.add(jLabel6);

        jLabelTxtPreguntasIncorrectas.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabelTxtPreguntasIncorrectas.setText("20");
        jPanelTextosCreados.add(jLabelTxtPreguntasIncorrectas);

        jPanelScrollBarEstadisticas.add(jPanelTextosCreados, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 910, 210));

        jLabel4.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(253, 116, 1));
        jLabel4.setText("Textos creados");
        jPanelScrollBarEstadisticas.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        jPanelPreguntasRespondidas.setLayout(new java.awt.GridLayout(3, 2, 4, 4));

        jLabel5.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel5.setText("<html>Cantidad de preguntas respondidas por los estudiantes:</html>");
        jPanelPreguntasRespondidas.add(jLabel5);

        jLabelPreguntasEstudiantes.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabelPreguntasEstudiantes.setText("120");
        jPanelPreguntasRespondidas.add(jLabelPreguntasEstudiantes);

        jLabel8.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel8.setText("<html>Cantidad de preguntas acertadas por los estudiantes:</html>");
        jPanelPreguntasRespondidas.add(jLabel8);

        jLabelPreguntasAcertadasEstudiantes.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabelPreguntasAcertadasEstudiantes.setText("50");
        jPanelPreguntasRespondidas.add(jLabelPreguntasAcertadasEstudiantes);

        jLabel10.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel10.setText("<html>Cantidad de preguntas no acertadas por los estudiantes:</html>");
        jPanelPreguntasRespondidas.add(jLabel10);

        jLabelPreguntasNoAcertadas.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabelPreguntasNoAcertadas.setText("70");
        jPanelPreguntasRespondidas.add(jLabelPreguntasNoAcertadas);

        jPanelScrollBarEstadisticas.add(jPanelPreguntasRespondidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 910, 210));

        jLabel7.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(253, 116, 1));
        jLabel7.setText("Ranking de preguntas contestadas");
        jPanelScrollBarEstadisticas.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 660, 510, -1));

        labelPorcentajePreguntasAcertadas.setBackground(new java.awt.Color(255, 255, 255));
        labelPorcentajePreguntasAcertadas.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        labelPorcentajePreguntasAcertadas.setForeground(new java.awt.Color(253, 116, 1));
        labelPorcentajePreguntasAcertadas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPorcentajePreguntasAcertadas.setText("{Porcentaje1}");
        labelPorcentajePreguntasAcertadas.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(253, 116, 1), new java.awt.Color(253, 116, 1)));
        jPanelScrollBarEstadisticas.add(labelPorcentajePreguntasAcertadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 730, 170, 50));

        jLabel11.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(253, 116, 1));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("<html><p align=\"center\">Porcentaje de preguntas acertadas por los estudiantes.</p></html>");
        jLabel11.setAutoscrolls(true);
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelScrollBarEstadisticas.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 800, 310, 70));

        jLabel14.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(253, 116, 1));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("<html><p align=\"center\">Porcentaje de preguntas no acertadas por los estudiantes.</p></html>");
        jLabel14.setAutoscrolls(true);
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelScrollBarEstadisticas.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 800, 360, 70));

        jLabelPorcentajePreguntasNoAcertadas.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPorcentajePreguntasNoAcertadas.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jLabelPorcentajePreguntasNoAcertadas.setForeground(new java.awt.Color(253, 116, 1));
        jLabelPorcentajePreguntasNoAcertadas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPorcentajePreguntasNoAcertadas.setText("{Porcentaje2}");
        jLabelPorcentajePreguntasNoAcertadas.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(253, 116, 1), new java.awt.Color(253, 116, 1)));
        jPanelScrollBarEstadisticas.add(jLabelPorcentajePreguntasNoAcertadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 730, 170, 50));

        jLabel9.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(253, 116, 1));
        jLabel9.setText("Textos más leídos ");
        jPanelScrollBarEstadisticas.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 920, -1, -1));

        jTableOtrasEstadisticas.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jTableOtrasEstadisticas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Estudiante", "Porcentaje promedio de preguntas correctas", "Textos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableOtrasEstadisticas.setFocusable(false);
        jScrollPaneOtrasEstadisticas.setViewportView(jTableOtrasEstadisticas);

        jPanelScrollBarEstadisticas.add(jScrollPaneOtrasEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1280, 800, 190));

        jLabel12.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(253, 116, 1));
        jLabel12.setText("Otras estadísticas");
        jPanelScrollBarEstadisticas.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1230, -1, -1));

        jTableTextosMasLeidos.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jTableTextosMasLeidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Texto", "Popularidad", "Cantidad de preguntas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTextosMasLeidos.setFocusable(false);
        jScrollPaneTextosMasLeidos.setViewportView(jTableTextosMasLeidos);

        jPanelScrollBarEstadisticas.add(jScrollPaneTextosMasLeidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 980, 800, 200));
        jPanelScrollBarEstadisticas.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 1530, -1, -1));

        jScrollPaneEstadisticasD.setViewportView(jPanelScrollBarEstadisticas);

        bgPerfilDocente.add(jScrollPaneEstadisticasD, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 1060, 680));

        jPanel1.add(bgPerfilDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 953));

        bgInicioDocente.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(bgInicioDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 953));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgInicioDocente;
    private javax.swing.JPanel bgPerfilDocente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBreadCrumbsPerfilD;
    private javax.swing.JLabel jLabelCarreraPD;
    public javax.swing.JLabel jLabelNumTxtCreados;
    public javax.swing.JLabel jLabelPorcentajePreguntasNoAcertadas;
    public javax.swing.JLabel jLabelPreguntasAcertadasEstudiantes;
    public javax.swing.JLabel jLabelPreguntasEstudiantes;
    public javax.swing.JLabel jLabelPreguntasNoAcertadas;
    public javax.swing.JLabel jLabelTxtPreguntasCorrectas;
    public javax.swing.JLabel jLabelTxtPreguntasIncorrectas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelFotoPerfilD;
    private javax.swing.JPanel jPanelPreguntasRespondidas;
    private javax.swing.JPanel jPanelScrollBarEstadisticas;
    private javax.swing.JPanel jPanelTextosCreados;
    private javax.swing.JScrollPane jScrollPaneEstadisticasD;
    private javax.swing.JScrollPane jScrollPaneOtrasEstadisticas;
    private javax.swing.JScrollPane jScrollPaneTextosMasLeidos;
    public javax.swing.JTable jTableOtrasEstadisticas;
    public javax.swing.JTable jTableTextosMasLeidos;
    public javax.swing.JLabel labelPorcentajePreguntasAcertadas;
    // End of variables declaration//GEN-END:variables
}
