
package views;

import com.formdev.flatlaf.FlatLightLaf;


/**
 *
 * @author Vilberto Patricio
 */

public class InicioDocente extends javax.swing.JPanel {

    public InicioDocente() {
        initComponents();
        FlatLightLaf.setup(); //Modifica el diseño de los componentes de las interfaces graficas
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgInicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRanking = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgInicio.setBackground(new java.awt.Color(241, 243, 246));
        bgInicio.setPreferredSize(new java.awt.Dimension(1260, 850));
        bgInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(253, 116, 1));
        jLabel1.setText("Ranking de estudiantes");
        bgInicio.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(241, 243, 246));
        jScrollPane1.setFocusable(false);
        jScrollPane1.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N

        jTableRanking.setBackground(new java.awt.Color(241, 243, 246));
        jTableRanking.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jTableRanking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Posición", "Nombre del estudiante", "# Preguntas correctas", "# Preguntas incorrectas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableRanking.setShowGrid(false);
        jTableRanking.setShowHorizontalLines(true);
        jTableRanking.setShowVerticalLines(true);
        jScrollPane1.setViewportView(jTableRanking);

        bgInicio.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 1140, 660));

        add(bgInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1274, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRanking;
    // End of variables declaration//GEN-END:variables
}
