
package views;

import com.formdev.flatlaf.FlatLightLaf;


/**
 *
 * @author Vilberto Patricio
 */

public class jPanelCrearEjercicio1 extends javax.swing.JPanel {

    public jPanelCrearEjercicio1() {
        initComponents();
        FlatLightLaf.setup(); //Modifica el diseño de los componentes de las interfaces graficas
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgCrearGrupo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanelSubirArchivo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnDescargarModelo = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgCrearGrupo.setBackground(new java.awt.Color(241, 243, 246));
        bgCrearGrupo.setPreferredSize(new java.awt.Dimension(1260, 850));
        bgCrearGrupo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 22)); // NOI18N
        jLabel2.setText("Cargar archivo");
        bgCrearGrupo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel3.setText("Solo permite un archivo (.txt) con la estructura establecida.");
        bgCrearGrupo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 810, 40));

        jPanelSubirArchivo.setBackground(new java.awt.Color(241, 243, 246));
        jPanelSubirArchivo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(242, 227, 216), new java.awt.Color(242, 227, 216)));
        jPanelSubirArchivo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/upload.png"))); // NOI18N
        jPanelSubirArchivo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 130, 110));

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Subir archivo");
        jPanelSubirArchivo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 530, -1));

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Suelta en este area tu contenido para que se pueda subir.");
        jPanelSubirArchivo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 540, -1));

        bgCrearGrupo.add(jPanelSubirArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 600, 280));

        jLabel6.setFont(new java.awt.Font("Poppins", 1, 22)); // NOI18N
        jLabel6.setText("Descargar archivo");
        bgCrearGrupo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel7.setText("El siguiente archivo es un modelo de la estructura que debe de contener su archivo (.txt)");
        bgCrearGrupo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 870, 40));

        btnDescargarModelo.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        btnDescargarModelo.setForeground(new java.awt.Color(253, 116, 1));
        btnDescargarModelo.setText("Descargar");
        bgCrearGrupo.add(btnDescargarModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 190, 40));

        add(bgCrearGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 650));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgCrearGrupo;
    public javax.swing.JButton btnDescargarModelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JPanel jPanelSubirArchivo;
    // End of variables declaration//GEN-END:variables
}
