
package views;

import com.formdev.flatlaf.FlatLightLaf;


/**
 *
 * @author Vilberto Patricio
 */

public class jPanelCrearEjercicio2 extends javax.swing.JPanel {

    public jPanelCrearEjercicio2() {
        initComponents();
        FlatLightLaf.setup(); //Modifica el diseño de los componentes de las interfaces graficas
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanelCargarArchivo = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelDescripcion = new javax.swing.JLabel();
        jScrollPaneContenedor = new javax.swing.JScrollPane();
        jPanelContenedorTexto = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgPanelCargarArchivo.setBackground(new java.awt.Color(241, 243, 246));
        bgPanelCargarArchivo.setPreferredSize(new java.awt.Dimension(1260, 850));
        bgPanelCargarArchivo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Poppins", 1, 22)); // NOI18N
        jLabelTitulo.setText("Cargar archivo");
        bgPanelCargarArchivo.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabelDescripcion.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabelDescripcion.setText("Solo permite un archivo (.txt) con la estructura establecida.");
        bgPanelCargarArchivo.add(jLabelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 810, 40));

        jScrollPaneContenedor.setViewportView(jPanelContenedorTexto);

        bgPanelCargarArchivo.add(jScrollPaneContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 700, 350));

        add(bgPanelCargarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 650));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanelCargarArchivo;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelContenedorTexto;
    private javax.swing.JScrollPane jScrollPaneContenedor;
    // End of variables declaration//GEN-END:variables
}
