
package views;

import com.formdev.flatlaf.FlatLightLaf;
import controllers.LoginControllers;
import models.Usuario;

/**
 *
 * @author Vilberto Patricio
 */

public class Login extends javax.swing.JFrame {
    
    Usuario usuario;
    
    public Login() {
        initComponents();
        setTitle("Juez Cachimbo");
        setResizable(false);
        LoginControllers loginControllers=new LoginControllers(this,usuario);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgLogin = new javax.swing.JPanel();
        labelNombreApp = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtLoginCorreo = new javax.swing.JTextField();
        panelCorreo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtLoginClave = new javax.swing.JPasswordField();
        btnLoginIniciarSesion = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnLoginRegistrarse = new javax.swing.JButton();
        panelPassword = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgLogin.setBackground(new java.awt.Color(255, 255, 255));
        bgLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNombreApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombreApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Juez_cachimbp.png"))); // NOI18N
        bgLogin.add(labelNombreApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 46, 188, 153));

        jLabelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        bgLogin.add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 77, 89, 99));

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(85, 85, 85));
        jLabel3.setText("Correo electrónico");
        bgLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(85, 85, 85));
        jLabel4.setText("Contraseña");
        bgLogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        txtLoginCorreo.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtLoginCorreo.setForeground(new java.awt.Color(85, 85, 85));
        bgLogin.add(txtLoginCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 320, 40));

        panelCorreo.setBackground(new java.awt.Color(253, 116, 1));
        panelCorreo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/correo 3_1.png"))); // NOI18N
        panelCorreo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        bgLogin.add(panelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 40, 40));

        txtLoginClave.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtLoginClave.setForeground(new java.awt.Color(85, 85, 85));
        bgLogin.add(txtLoginClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 320, 40));

        btnLoginIniciarSesion.setBackground(new java.awt.Color(253, 116, 1));
        btnLoginIniciarSesion.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        btnLoginIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnLoginIniciarSesion.setText("Iniciar sesión");
        btnLoginIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLoginIniciarSesion.setFocusable(false);
        bgLogin.add(btnLoginIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 360, 40));
        bgLogin.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 600, 360, 10));

        btnLoginRegistrarse.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        btnLoginRegistrarse.setForeground(new java.awt.Color(253, 116, 1));
        btnLoginRegistrarse.setText("Registrarse");
        btnLoginRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLoginRegistrarse.setFocusable(false);
        bgLogin.add(btnLoginRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 630, 360, 40));

        panelPassword.setBackground(new java.awt.Color(253, 116, 1));
        panelPassword.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/candado 3.png"))); // NOI18N
        panelPassword.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        bgLogin.add(panelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        FlatLightLaf.setup(); //Modifica el diseño de los componentes de las interfaces graficas

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgLogin;
    public javax.swing.JButton btnLoginIniciarSesion;
    public javax.swing.JButton btnLoginRegistrarse;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelNombreApp;
    private javax.swing.JPanel panelCorreo;
    private javax.swing.JPanel panelPassword;
    public javax.swing.JPasswordField txtLoginClave;
    public javax.swing.JTextField txtLoginCorreo;
    // End of variables declaration//GEN-END:variables
}
