
package views;

import com.formdev.flatlaf.FlatLightLaf; //Es una libreria de Java que permite darle un diseño mas moderno a las interfaces. Esta libreria esta en la web.
import java.awt.BorderLayout;
import javax.swing.JPanel;
import models.Usuario;
import controllers.PanelDocenteController;


public class PanelDocente extends javax.swing.JFrame {

    PanelDocenteController panelDocenteController;
    public Usuario usuario;
    
    public PanelDocente() {
        initComponents();
        setTitle("Juez Cachimbo");
        setResizable(false); //La aplicacion no sera responsiva
        InitContent();
        panelDocenteController=new PanelDocenteController(this);
    }
    
    public void setDocenteLabel(){
        jLabelDocente.setText(usuario.getApellidos()+" ,"+usuario.getNombres());
    }
    
    //Metodo para iniciar un contenedor
    public void InitContent(){
        showJPanel(new InicioDocente());
    }
    
    //Metodo que permite mostrar un panel en relación a uno de los botones del menú
    public void showJPanel(JPanel p){
        p.setSize(1260, 953); //El nuevo panel tendra la misma dimension del contenedor principal
        p.setLocation(0, 0); //El nuevo panel se colocara en la posicion (0, 0)
        
        contenedorPrincipalD.removeAll();
        contenedorPrincipalD.add(p, BorderLayout.CENTER);
        contenedorPrincipalD.revalidate();
        contenedorPrincipalD.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelOpcionesDocente = new javax.swing.JPanel();
        jPanelInicioD = new javax.swing.JPanel();
        jLabelInicio = new javax.swing.JLabel();
        jPanelPerfilD = new javax.swing.JPanel();
        jLabelPerfil = new javax.swing.JLabel();
        jPanelSeguimientoD = new javax.swing.JPanel();
        jLabelSeguimiento = new javax.swing.JLabel();
        jPanelCerrarSesionD = new javax.swing.JPanel();
        jLabelCerrarSesion = new javax.swing.JLabel();
        jPanelEstadisticasGeneralesD = new javax.swing.JPanel();
        jLabelEstadisticaGenerales = new javax.swing.JLabel();
        jLabelDocente = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        contenedorPrincipalD = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1650, 953));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelOpcionesDocente.setBackground(new java.awt.Color(255, 255, 255));
        jPanelOpcionesDocente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelInicioD.setBackground(new java.awt.Color(255, 255, 255));
        jPanelInicioD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelInicioD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inicio-tamanio1x.png"))); // NOI18N
        jPanelInicioD.add(jLabelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 180, 60));

        jPanelOpcionesDocente.add(jPanelInicioD, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 390, 62));

        jPanelPerfilD.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPerfilD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelPerfilD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/perfil-tamanio1x.png"))); // NOI18N
        jPanelPerfilD.add(jLabelPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 150, 60));

        jPanelOpcionesDocente.add(jPanelPerfilD, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 390, 62));

        jPanelSeguimientoD.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSeguimientoD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelSeguimientoD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSeguimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seguimiento-tamanio-1x.png"))); // NOI18N
        jPanelSeguimientoD.add(jLabelSeguimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 230, 60));

        jPanelOpcionesDocente.add(jPanelSeguimientoD, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 390, 62));

        jPanelCerrarSesionD.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCerrarSesionD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelCerrarSesionD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/log-out-tamanio1x.png"))); // NOI18N
        jPanelCerrarSesionD.add(jLabelCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 60));

        jPanelOpcionesDocente.add(jPanelCerrarSesionD, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 830, 390, 62));

        jPanelEstadisticasGeneralesD.setBackground(new java.awt.Color(255, 255, 255));
        jPanelEstadisticasGeneralesD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelEstadisticasGeneralesD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelEstadisticaGenerales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/estadisticas-generales-tamanio-1x.png"))); // NOI18N
        jPanelEstadisticasGeneralesD.add(jLabelEstadisticaGenerales, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 330, 60));

        jPanelOpcionesDocente.add(jPanelEstadisticasGeneralesD, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 390, 62));

        jLabelDocente.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jLabelDocente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDocente.setText("Docente");
        jPanelOpcionesDocente.add(jLabelDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 370, 30));

        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Juez_cachimbp.png"))); // NOI18N
        jPanelOpcionesDocente.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 210, 100));

        icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        jPanelOpcionesDocente.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 100, 100));

        getContentPane().add(jPanelOpcionesDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 953));

        contenedorPrincipalD.setBackground(new java.awt.Color(241, 243, 246));

        javax.swing.GroupLayout contenedorPrincipalDLayout = new javax.swing.GroupLayout(contenedorPrincipalD);
        contenedorPrincipalD.setLayout(contenedorPrincipalDLayout);
        contenedorPrincipalDLayout.setHorizontalGroup(
            contenedorPrincipalDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contenedorPrincipalDLayout.setVerticalGroup(
            contenedorPrincipalDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 953, Short.MAX_VALUE)
        );

        getContentPane().add(contenedorPrincipalD, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 1260, 953));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        FlatLightLaf.setup(); //Permite iniciar la libreria y esta modifica el diseño de los componentes.
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelDocente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel contenedorPrincipalD;
    private javax.swing.JLabel icon;
    public javax.swing.JLabel jLabelCerrarSesion;
    private javax.swing.JLabel jLabelDocente;
    public javax.swing.JLabel jLabelEstadisticaGenerales;
    public javax.swing.JLabel jLabelInicio;
    public javax.swing.JLabel jLabelPerfil;
    public javax.swing.JLabel jLabelSeguimiento;
    public javax.swing.JPanel jPanelCerrarSesionD;
    public javax.swing.JPanel jPanelEstadisticasGeneralesD;
    public javax.swing.JPanel jPanelInicioD;
    private javax.swing.JPanel jPanelOpcionesDocente;
    public javax.swing.JPanel jPanelPerfilD;
    public javax.swing.JPanel jPanelSeguimientoD;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the usuario
     */
    public Usuario getUsuario() {
        return usuario;
    }

    /**
     * @param usuario the usuario to set
     */
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
}
