
package views;

import com.formdev.flatlaf.FlatLightLaf; //Es una libreria de Java que permite darle un diseño mas moderno a las interfaces. Esta libreria esta en la web.
import java.awt.BorderLayout;
import javax.swing.JPanel;


/**
 *
 * @author Vilberto Patricio
 */

public class PanelEstudiante extends javax.swing.JFrame {

    public PanelEstudiante() {
        initComponents();
        setTitle("Juez Cachimbo");
        setResizable(false); //La aplicacion no sera responsiva
        InitContent();
    }
    
    //Metodo para iniciar un contenedor
    public void InitContent(){
        showJPanel(new InicioEstudiante());
    }
    
    //Metodo que permite mostrar un panel en relación a uno de los botones del menú
    public void showJPanel(JPanel p){
        p.setSize(1260, 850); //El nuevo panel tendra la misma dimension del contenedor principal
        p.setLocation(0, 0); //El nuevo panel se colocara en la posicion (0, 0)
        
        contenedorPrincipalE.removeAll();
        contenedorPrincipalE.add(p, BorderLayout.CENTER);
        contenedorPrincipalE.revalidate();
        contenedorPrincipalE.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelOpcionesEstudiante = new javax.swing.JPanel();
        jPanelInicioE = new javax.swing.JPanel();
        jLabelInicio = new javax.swing.JLabel();
        jPanelPerfilE = new javax.swing.JPanel();
        jLabelPerfil = new javax.swing.JLabel();
        jPanelPracticarE = new javax.swing.JPanel();
        jLabelPracticar = new javax.swing.JLabel();
        jPanelCerrarSesionE = new javax.swing.JPanel();
        jLabelCerrarSesion = new javax.swing.JLabel();
        jPanelEstadisticaE = new javax.swing.JPanel();
        jLabelEstadistica = new javax.swing.JLabel();
        jLabelEstudiante = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        jPanelBusquedaEstudiante = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        contenedorPrincipalE = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1650, 953));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelOpcionesEstudiante.setBackground(new java.awt.Color(255, 255, 255));
        jPanelOpcionesEstudiante.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelInicioE.setBackground(new java.awt.Color(255, 255, 255));
        jPanelInicioE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelInicioE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inicio-tamanio1x.png"))); // NOI18N
        jPanelInicioE.add(jLabelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 180, 60));

        jPanelOpcionesEstudiante.add(jPanelInicioE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 390, 62));

        jPanelPerfilE.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPerfilE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelPerfilE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/perfil-tamanio1x.png"))); // NOI18N
        jPanelPerfilE.add(jLabelPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 150, 60));

        jPanelOpcionesEstudiante.add(jPanelPerfilE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 390, 62));

        jPanelPracticarE.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPracticarE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelPracticarE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPracticar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/practicar-tamanio1x.png"))); // NOI18N
        jPanelPracticarE.add(jLabelPracticar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 200, 60));

        jPanelOpcionesEstudiante.add(jPanelPracticarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 390, 62));

        jPanelCerrarSesionE.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCerrarSesionE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelCerrarSesionE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/log-out-tamanio1x.png"))); // NOI18N
        jPanelCerrarSesionE.add(jLabelCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 60));

        jPanelOpcionesEstudiante.add(jPanelCerrarSesionE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 830, 390, 62));

        jPanelEstadisticaE.setBackground(new java.awt.Color(255, 255, 255));
        jPanelEstadisticaE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelEstadisticaE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelEstadistica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/estadisticas-tamanio1x.png"))); // NOI18N
        jPanelEstadisticaE.add(jLabelEstadistica, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 250, 60));

        jPanelOpcionesEstudiante.add(jPanelEstadisticaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 390, 62));

        jLabelEstudiante.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jLabelEstudiante.setText("Estudiante");
        jPanelOpcionesEstudiante.add(jLabelEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Juez_cachimbp.png"))); // NOI18N
        jPanelOpcionesEstudiante.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 210, 100));

        icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        jPanelOpcionesEstudiante.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 100, 100));

        getContentPane().add(jPanelOpcionesEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 953));

        jPanelBusquedaEstudiante.setBackground(new java.awt.Color(241, 243, 246));
        jPanelBusquedaEstudiante.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(85, 85, 85));
        jPanelBusquedaEstudiante.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 419, 32));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search 1.png"))); // NOI18N
        jPanelBusquedaEstudiante.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, 30, 30));

        getContentPane().add(jPanelBusquedaEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 1260, 90));

        contenedorPrincipalE.setBackground(new java.awt.Color(241, 243, 246));
        contenedorPrincipalE.setPreferredSize(new java.awt.Dimension(1260, 850));

        javax.swing.GroupLayout contenedorPrincipalELayout = new javax.swing.GroupLayout(contenedorPrincipalE);
        contenedorPrincipalE.setLayout(contenedorPrincipalELayout);
        contenedorPrincipalELayout.setHorizontalGroup(
            contenedorPrincipalELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1260, Short.MAX_VALUE)
        );
        contenedorPrincipalELayout.setVerticalGroup(
            contenedorPrincipalELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );

        getContentPane().add(contenedorPrincipalE, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 93, 1260, 850));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        FlatLightLaf.setup(); //Permite iniciar la libreria y esta modifica el diseño de los componentes.
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel contenedorPrincipalE;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabelCerrarSesion;
    public javax.swing.JLabel jLabelEstadistica;
    private javax.swing.JLabel jLabelEstudiante;
    public javax.swing.JLabel jLabelInicio;
    public javax.swing.JLabel jLabelPerfil;
    public javax.swing.JLabel jLabelPracticar;
    private javax.swing.JPanel jPanelBusquedaEstudiante;
    public javax.swing.JPanel jPanelCerrarSesionE;
    public javax.swing.JPanel jPanelEstadisticaE;
    public javax.swing.JPanel jPanelInicioE;
    private javax.swing.JPanel jPanelOpcionesEstudiante;
    public javax.swing.JPanel jPanelPerfilE;
    public javax.swing.JPanel jPanelPracticarE;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
