
package views;

import com.formdev.flatlaf.FlatLightLaf;


/**
 *
 * @author Vilberto Patricio
 */

public class PerfilDocente extends javax.swing.JPanel {

    public PerfilDocente() {
        initComponents();
        FlatLightLaf.setup(); //Modifica el diseño de los componentes de las interfaces graficas
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPerfilDocente = new javax.swing.JPanel();
        jLabelBreadCrumbsPerfilD = new javax.swing.JLabel();
        jLabelNombreApellidosDocenteP = new javax.swing.JLabel();
        jLabelGrupo = new javax.swing.JLabel();
        jPanelFotoPerfilD = new javax.swing.JPanel();
        jLabelCarreraPD = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelEG = new javax.swing.JLabel();
        jPanelEstadisticaDG1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabelEGTxtAsignados = new javax.swing.JLabel();
        jPanelEstadisticaDG2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabelEGPorcentajePregCorrectas = new javax.swing.JLabel();
        jPanelEstadisticaDG3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabelEGCantPreguntasResueltas = new javax.swing.JLabel();
        btnCrearGrupoD = new javax.swing.JButton();
        btnEditarDatosPersonalesD = new javax.swing.JButton();
        jLabelUsernameDocenteP = new javax.swing.JLabel();
        jComboBoxGruposDocente = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgPerfilDocente.setBackground(new java.awt.Color(241, 243, 246));
        bgPerfilDocente.setPreferredSize(new java.awt.Dimension(1260, 850));
        bgPerfilDocente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelBreadCrumbsPerfilD.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabelBreadCrumbsPerfilD.setText("Juez Cachimbo / Perfil");
        bgPerfilDocente.add(jLabelBreadCrumbsPerfilD, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabelNombreApellidosDocenteP.setFont(new java.awt.Font("Poppins SemiBold", 0, 20)); // NOI18N
        jLabelNombreApellidosDocenteP.setText("{Nombres}, {Apellidos}");
        bgPerfilDocente.add(jLabelNombreApellidosDocenteP, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 450, -1));

        jLabelGrupo.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabelGrupo.setText("Grupo:");
        bgPerfilDocente.add(jLabelGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 70, -1));

        jPanelFotoPerfilD.setBackground(new java.awt.Color(241, 243, 246));
        jPanelFotoPerfilD.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(243, 213, 190), new java.awt.Color(243, 213, 190)));

        javax.swing.GroupLayout jPanelFotoPerfilDLayout = new javax.swing.GroupLayout(jPanelFotoPerfilD);
        jPanelFotoPerfilD.setLayout(jPanelFotoPerfilDLayout);
        jPanelFotoPerfilDLayout.setHorizontalGroup(
            jPanelFotoPerfilDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );
        jPanelFotoPerfilDLayout.setVerticalGroup(
            jPanelFotoPerfilDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );

        bgPerfilDocente.add(jPanelFotoPerfilD, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 150, 100, 100));

        jLabelCarreraPD.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabelCarreraPD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCarreraPD.setText("{Carrera}");
        bgPerfilDocente.add(jLabelCarreraPD, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 260, 100, -1));

        jSeparator1.setForeground(new java.awt.Color(243, 213, 190));
        bgPerfilDocente.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 790, 10));

        jLabelEG.setFont(new java.awt.Font("Poppins SemiBold", 0, 20)); // NOI18N
        jLabelEG.setForeground(new java.awt.Color(253, 116, 1));
        jLabelEG.setText("Estadísticas generales");
        bgPerfilDocente.add(jLabelEG, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, -1));

        jPanelEstadisticaDG1.setBackground(new java.awt.Color(241, 243, 246));
        jPanelEstadisticaDG1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(243, 213, 190), new java.awt.Color(243, 213, 190)));
        jPanelEstadisticaDG1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel6.setText("<html><p>Cantidad de textos asignados a su grupo</p></html>");
        jPanelEstadisticaDG1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 320, 48));

        jLabelEGTxtAsignados.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabelEGTxtAsignados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEGTxtAsignados.setText("{Cantidad}");
        jPanelEstadisticaDG1.add(jLabelEGTxtAsignados, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, 48));

        bgPerfilDocente.add(jPanelEstadisticaDG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 360, 175));

        jPanelEstadisticaDG2.setBackground(new java.awt.Color(241, 243, 246));
        jPanelEstadisticaDG2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(243, 213, 190), new java.awt.Color(243, 213, 190)));
        jPanelEstadisticaDG2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel8.setText("<html>Porcentaje de preguntas correctas de su grupo</html>");
        jPanelEstadisticaDG2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 320, 48));

        jLabelEGPorcentajePregCorrectas.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabelEGPorcentajePregCorrectas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEGPorcentajePregCorrectas.setText("{Porcentaje}");
        jPanelEstadisticaDG2.add(jLabelEGPorcentajePregCorrectas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, 48));

        bgPerfilDocente.add(jPanelEstadisticaDG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, 360, 175));

        jPanelEstadisticaDG3.setBackground(new java.awt.Color(241, 243, 246));
        jPanelEstadisticaDG3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(243, 213, 190), new java.awt.Color(243, 213, 190)));
        jPanelEstadisticaDG3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel7.setText("<html>Cantidad de preguntas resueltas por todos sus alumnos</html>");
        jPanelEstadisticaDG3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 320, 48));

        jLabelEGCantPreguntasResueltas.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabelEGCantPreguntasResueltas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEGCantPreguntasResueltas.setText("{Cantidad}");
        jPanelEstadisticaDG3.add(jLabelEGCantPreguntasResueltas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, 48));

        bgPerfilDocente.add(jPanelEstadisticaDG3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 610, 360, 175));

        btnCrearGrupoD.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        btnCrearGrupoD.setForeground(new java.awt.Color(253, 116, 1));
        btnCrearGrupoD.setText("Crear grupo");
        btnCrearGrupoD.setFocusable(false);
        bgPerfilDocente.add(btnCrearGrupoD, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 850, 240, 40));

        btnEditarDatosPersonalesD.setBackground(new java.awt.Color(253, 116, 1));
        btnEditarDatosPersonalesD.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        btnEditarDatosPersonalesD.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarDatosPersonalesD.setText("Editar datos personales");
        btnEditarDatosPersonalesD.setFocusable(false);
        bgPerfilDocente.add(btnEditarDatosPersonalesD, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 850, 260, 40));

        jLabelUsernameDocenteP.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabelUsernameDocenteP.setText("{Username}");
        bgPerfilDocente.add(jLabelUsernameDocenteP, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 340, -1));

        jComboBoxGruposDocente.setFont(new java.awt.Font("Poppins", 0, 17)); // NOI18N
        jComboBoxGruposDocente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grupo 1", "Grupo 2", "Grupo 3", "Grupo 4" }));
        bgPerfilDocente.add(jComboBoxGruposDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));

        add(bgPerfilDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 953));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPerfilDocente;
    private javax.swing.JButton btnCrearGrupoD;
    private javax.swing.JButton btnEditarDatosPersonalesD;
    private javax.swing.JComboBox<String> jComboBoxGruposDocente;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelBreadCrumbsPerfilD;
    private javax.swing.JLabel jLabelCarreraPD;
    private javax.swing.JLabel jLabelEG;
    private javax.swing.JLabel jLabelEGCantPreguntasResueltas;
    private javax.swing.JLabel jLabelEGPorcentajePregCorrectas;
    private javax.swing.JLabel jLabelEGTxtAsignados;
    private javax.swing.JLabel jLabelGrupo;
    private javax.swing.JLabel jLabelNombreApellidosDocenteP;
    private javax.swing.JLabel jLabelUsernameDocenteP;
    private javax.swing.JPanel jPanelEstadisticaDG1;
    private javax.swing.JPanel jPanelEstadisticaDG2;
    private javax.swing.JPanel jPanelEstadisticaDG3;
    private javax.swing.JPanel jPanelFotoPerfilD;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
