
package views;

import com.formdev.flatlaf.FlatLightLaf;

public class PerfilEstudiante extends javax.swing.JPanel {

    public PerfilEstudiante() {
        initComponents();
        FlatLightLaf.setup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPerfil = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelEstadisticaG1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabelEGPreguntasCorrectas = new javax.swing.JLabel();
        jPanelEstadisticaG2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabelEGPorcentajeTxtCorrectos = new javax.swing.JLabel();
        jPanelEstadisticaG3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabelEGPorcentajePreguntasCorrectas = new javax.swing.JLabel();
        jPanelEstadisticaG4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabelEGTxtLeidos = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelFotoPerfil = new javax.swing.JPanel();
        jLabelNombreApellidosEstudianteP = new javax.swing.JLabel();
        jLabelUsernameEstudianteP = new javax.swing.JLabel();
        jLabelRankingP = new javax.swing.JLabel();
        btnEditarDatosPersonales = new javax.swing.JButton();
        jLabelBCPerfilE = new javax.swing.JLabel();

        bgPerfil.setBackground(new java.awt.Color(241, 243, 246));
        bgPerfil.setPreferredSize(new java.awt.Dimension(1260, 850));
        bgPerfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(253, 116, 1));
        jLabel1.setText("Estadísticas generales");
        bgPerfil.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        jPanelEstadisticaG1.setBackground(new java.awt.Color(241, 243, 246));
        jPanelEstadisticaG1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(243, 213, 190), new java.awt.Color(243, 213, 190)));
        jPanelEstadisticaG1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel6.setText("Cantidad de preguntas correctas");
        jPanelEstadisticaG1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 48));

        jLabelEGPreguntasCorrectas.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabelEGPreguntasCorrectas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEGPreguntasCorrectas.setText("{Cantidad}");
        jPanelEstadisticaG1.add(jLabelEGPreguntasCorrectas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, 48));

        bgPerfil.add(jPanelEstadisticaG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 360, 175));

        jPanelEstadisticaG2.setBackground(new java.awt.Color(241, 243, 246));
        jPanelEstadisticaG2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(243, 213, 190), new java.awt.Color(243, 213, 190)));
        jPanelEstadisticaG2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel8.setText("<html>Porcentaje de textos en los que acerto todas las preguntas</html>");
        jPanelEstadisticaG2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 320, 48));

        jLabelEGPorcentajeTxtCorrectos.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabelEGPorcentajeTxtCorrectos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEGPorcentajeTxtCorrectos.setText("{Porcentaje}");
        jPanelEstadisticaG2.add(jLabelEGPorcentajeTxtCorrectos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, 48));

        bgPerfil.add(jPanelEstadisticaG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, 360, 175));

        jPanelEstadisticaG3.setBackground(new java.awt.Color(241, 243, 246));
        jPanelEstadisticaG3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(243, 213, 190), new java.awt.Color(243, 213, 190)));
        jPanelEstadisticaG3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel10.setText("<html>Porcentaje de preguntas correctas en total</html>");
        jPanelEstadisticaG3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 320, 48));

        jLabelEGPorcentajePreguntasCorrectas.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabelEGPorcentajePreguntasCorrectas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEGPorcentajePreguntasCorrectas.setText("{Porcentaje}");
        jPanelEstadisticaG3.add(jLabelEGPorcentajePreguntasCorrectas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, 48));

        bgPerfil.add(jPanelEstadisticaG3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 530, 360, 175));

        jPanelEstadisticaG4.setBackground(new java.awt.Color(241, 243, 246));
        jPanelEstadisticaG4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(243, 213, 190), new java.awt.Color(243, 213, 190)));
        jPanelEstadisticaG4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel7.setText("Cantidad de texto leídos");
        jPanelEstadisticaG4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 48));

        jLabelEGTxtLeidos.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabelEGTxtLeidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEGTxtLeidos.setText("{Cantidad}");
        jPanelEstadisticaG4.add(jLabelEGTxtLeidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, 48));

        bgPerfil.add(jPanelEstadisticaG4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, 360, 175));

        jSeparator1.setForeground(new java.awt.Color(243, 213, 190));
        bgPerfil.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 790, 10));

        jPanelFotoPerfil.setBackground(new java.awt.Color(241, 243, 246));
        jPanelFotoPerfil.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(243, 213, 190), new java.awt.Color(243, 213, 190)));

        javax.swing.GroupLayout jPanelFotoPerfilLayout = new javax.swing.GroupLayout(jPanelFotoPerfil);
        jPanelFotoPerfil.setLayout(jPanelFotoPerfilLayout);
        jPanelFotoPerfilLayout.setHorizontalGroup(
            jPanelFotoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );
        jPanelFotoPerfilLayout.setVerticalGroup(
            jPanelFotoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );

        bgPerfil.add(jPanelFotoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 100, 100, 100));

        jLabelNombreApellidosEstudianteP.setFont(new java.awt.Font("Poppins SemiBold", 0, 20)); // NOI18N
        jLabelNombreApellidosEstudianteP.setText("{Nombres}, {Apellidos}");
        bgPerfil.add(jLabelNombreApellidosEstudianteP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 450, -1));

        jLabelUsernameEstudianteP.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabelUsernameEstudianteP.setText("{Username}");
        bgPerfil.add(jLabelUsernameEstudianteP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 340, -1));

        jLabelRankingP.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabelRankingP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRankingP.setText("{Ranking}");
        bgPerfil.add(jLabelRankingP, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 210, 100, -1));

        btnEditarDatosPersonales.setBackground(new java.awt.Color(253, 116, 1));
        btnEditarDatosPersonales.setFont(new java.awt.Font("Poppins SemiBold", 0, 20)); // NOI18N
        btnEditarDatosPersonales.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarDatosPersonales.setText("Editar datos personales");
        btnEditarDatosPersonales.setFocusable(false);
        bgPerfil.add(btnEditarDatosPersonales, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 740, 350, 50));

        jLabelBCPerfilE.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabelBCPerfilE.setText("Juez Cachimbo / Perfil");
        bgPerfil.add(jLabelBCPerfilE, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPerfil;
    private javax.swing.JButton btnEditarDatosPersonales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelBCPerfilE;
    private javax.swing.JLabel jLabelEGPorcentajePreguntasCorrectas;
    private javax.swing.JLabel jLabelEGPorcentajeTxtCorrectos;
    private javax.swing.JLabel jLabelEGPreguntasCorrectas;
    private javax.swing.JLabel jLabelEGTxtLeidos;
    private javax.swing.JLabel jLabelNombreApellidosEstudianteP;
    private javax.swing.JLabel jLabelRankingP;
    private javax.swing.JLabel jLabelUsernameEstudianteP;
    private javax.swing.JPanel jPanelEstadisticaG1;
    private javax.swing.JPanel jPanelEstadisticaG2;
    private javax.swing.JPanel jPanelEstadisticaG3;
    private javax.swing.JPanel jPanelEstadisticaG4;
    private javax.swing.JPanel jPanelFotoPerfil;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
