
package views;

import com.formdev.flatlaf.FlatLightLaf;

public class PerfilEstudiante extends javax.swing.JPanel {

    public PerfilEstudiante() {
        initComponents();
        FlatLightLaf.setup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPerfil = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnEditarDatosPersonales = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();

        bgPerfil.setBackground(new java.awt.Color(241, 243, 246));
        bgPerfil.setPreferredSize(new java.awt.Dimension(1260, 850));
        bgPerfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(253, 116, 1));
        jLabel1.setText("Estadísticas generales");
        bgPerfil.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        jPanel1.setBackground(new java.awt.Color(241, 243, 246));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(243, 213, 190), new java.awt.Color(243, 213, 190)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel6.setText("Cantidad de preguntas correctas");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 48));

        jLabel12.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("{Cantidad}");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, 48));

        bgPerfil.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 360, 175));

        jPanel5.setBackground(new java.awt.Color(241, 243, 246));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(243, 213, 190), new java.awt.Color(243, 213, 190)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel8.setText("<html>Porcentaje de textos en los que acerto todas las preguntas</html>");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 320, 48));

        jLabel14.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("{Porcentaje}");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, 48));

        bgPerfil.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, 360, 175));

        jPanel6.setBackground(new java.awt.Color(241, 243, 246));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(243, 213, 190), new java.awt.Color(243, 213, 190)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel10.setText("<html>Porcentaje de preguntas correctas en total</html>");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 320, 48));

        jLabel13.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("{Porcentaje}");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, 48));

        bgPerfil.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 530, 360, 175));

        jPanel7.setBackground(new java.awt.Color(241, 243, 246));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(243, 213, 190), new java.awt.Color(243, 213, 190)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel7.setText("Cantidad de texto leídos");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 48));

        jLabel11.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("{Cantidad}");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, 48));

        bgPerfil.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, 360, 175));

        jSeparator1.setForeground(new java.awt.Color(243, 213, 190));
        bgPerfil.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 790, 10));

        jPanel2.setBackground(new java.awt.Color(241, 243, 246));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(243, 213, 190), new java.awt.Color(243, 213, 190)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );

        bgPerfil.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 100, 100, 100));

        jLabel2.setFont(new java.awt.Font("Poppins SemiBold", 0, 20)); // NOI18N
        jLabel2.setText("{Nombres}, {Apellidos}");
        bgPerfil.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 450, -1));

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel3.setText("{Username}");
        bgPerfil.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 340, -1));

        jLabel4.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("{Ranking}");
        bgPerfil.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 210, 100, -1));

        btnEditarDatosPersonales.setBackground(new java.awt.Color(253, 116, 1));
        btnEditarDatosPersonales.setFont(new java.awt.Font("Poppins SemiBold", 0, 20)); // NOI18N
        btnEditarDatosPersonales.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarDatosPersonales.setText("Editar datos personales");
        btnEditarDatosPersonales.setFocusable(false);
        bgPerfil.add(btnEditarDatosPersonales, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 740, 350, 50));

        jLabel26.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel26.setText("Juez Cachimbo / Perfil");
        bgPerfil.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPerfil;
    private javax.swing.JButton btnEditarDatosPersonales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
