/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import com.formdev.flatlaf.FlatLightLaf;

/**
 *
 * @author Usuario
 */
public class PracticarResolucion extends javax.swing.JFrame {

    /**
     * Creates new form PracticarResolucion
     */
    public PracticarResolucion() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel26.setText("Juez Cachimbo / Practicar / Resolución");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jScrollPane1.setColumnHeaderView(null);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabel10.setText("ID: {id_texto}");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));
        jPanel7.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 870, -1));

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jLabel11.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel11.setText("<html><p>knbrebvubervubpievbibiwvebibpeiwvbibbwib2yievbypbwylkbypwveolqhvwvdhfvjlvlasaljevouvaeLorem ipsum dolor sit amet consectetur adipisicing elit. Fuga fugiat dolorem voluptatem architecto nulla dicta, distinctio natus accusamus sit temporibus et error tempore voluptates in optio quasi sequi? Eaque accusantium maiores eum modi reprehenderit voluptates praesentium tenetur vero? Et officia assumenda culpa, quos eaque magnam dolores facere eum quod nemo, neque, quisquam obcaecati asperiores ad dignissimos reprehenderit quaerat eligendi tempore. Doloremque deserunt distinctio qui hic ipsum, eius nulla iusto dolorem laborum molestias, saepe eveniet odio, fuga officia! Maiores corrupti animi quas officiis alias reiciendis pariatur quibusdam eos iure sit. Debitis unde, porro dicta provident blanditiis ea laudantium quasi sed, quam autem numquam cumque deserunt iure ipsa minima nihil suscipit, temporibus alias ad aperiam? kjryiqvveaiuucgnqob73qct4bjehdcwisivsdibibdskwebviunuwweipuvweubevubevefvbuoevuibeuibvefuiebvbdkjnajkñdnjkfdibeivew Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga fugiat dolorem voluptatem architecto nulla dicta, distinctio natus accusamus sit temporibus et error tempore voluptates in optio quasi sequi? Eaque accusantium maiores eum modi reprehenderit voluptates praesentium tenetur vero? Et officia assumenda culpa, quos eaque magnam dolores facere eum quod nemo, neque, quisquam obcaecati asperiores ad dignissimos reprehenderit quaerat eligendi tempore. Doloremque deserunt distinctio qui hic ipsum, eius nulla iusto dolorem laborum molestias, saepe eveniet odio, fuga officia! Maiores corrupti animi quas officiis alias reiciendis pariatur quibusdam eos iure sit. Debitis unde, porro dicta provident blanditiis ea laudantium quasi sed, quam autem numquam cumque deserunt iure ipsa minima nihil suscipit, temporibus alias ad aperiam? </p></html>");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel11.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel6.add(jLabel11);

        jPanel7.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 880, 490));

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel3.setLayout(new java.awt.GridLayout(9, 0));

        jLabel1.setText("jLabel1");
        jPanel3.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabel2.setText("Pregunta 01");
        jPanel3.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel3.setText("Enunciado");
        jPanel3.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabel4.setText("Alternativas");
        jPanel3.add(jLabel4);

        jRadioButton1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jRadioButton1.setText("A) Alternativa 1");
        jPanel3.add(jRadioButton1);

        jRadioButton2.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jRadioButton2.setText("B) Alternativa 2");
        jPanel3.add(jRadioButton2);

        jRadioButton3.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jRadioButton3.setText("jRadioButton3");
        jPanel3.add(jRadioButton3);

        jRadioButton4.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jRadioButton4.setText("jRadioButton4");
        jPanel3.add(jRadioButton4);

        jPanel2.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(9, 0));

        jLabel5.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel4.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel4.add(jLabel6);

        jLabel7.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel4.add(jLabel7);

        jRadioButton5.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jRadioButton5.setText("jRadioButton5");
        jPanel4.add(jRadioButton5);

        jRadioButton6.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jRadioButton6.setText("jRadioButton6");
        jPanel4.add(jRadioButton6);

        jRadioButton7.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jRadioButton7.setText("jRadioButton7");
        jPanel4.add(jRadioButton7);

        jRadioButton8.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jRadioButton8.setText("jRadioButton8");
        jPanel4.add(jRadioButton8);

        jRadioButton9.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jRadioButton9.setText("jRadioButton9");
        jPanel4.add(jRadioButton9);

        jPanel2.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(9, 0));

        jLabel9.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel5.add(jLabel9);

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel5.add(jLabel8);

        jLabel12.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel5.add(jLabel12);

        jRadioButton10.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jRadioButton10.setText("jRadioButton10");
        jPanel5.add(jRadioButton10);

        jRadioButton11.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jRadioButton11.setText("jRadioButton11");
        jPanel5.add(jRadioButton11);

        jRadioButton12.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jRadioButton12.setText("jRadioButton12");
        jPanel5.add(jRadioButton12);

        jRadioButton13.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jRadioButton13.setText("jRadioButton13");
        jPanel5.add(jRadioButton13);

        jRadioButton14.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jRadioButton14.setText("jRadioButton14");
        jPanel5.add(jRadioButton14);

        jPanel2.add(jPanel5);

        jPanel8.setLayout(new java.awt.GridLayout(9, 0));

        jLabel13.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel8.add(jLabel13);

        jLabel14.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel8.add(jLabel14);

        jLabel15.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabel15.setText("jLabel15");
        jPanel8.add(jLabel15);

        jRadioButton15.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jRadioButton15.setText("jRadioButton15");
        jPanel8.add(jRadioButton15);

        jRadioButton16.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jRadioButton16.setText("jRadioButton16");
        jPanel8.add(jRadioButton16);

        jRadioButton17.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jRadioButton17.setText("jRadioButton17");
        jPanel8.add(jRadioButton17);

        jRadioButton18.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jRadioButton18.setText("jRadioButton18");
        jPanel8.add(jRadioButton18);

        jRadioButton19.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jRadioButton19.setText("jRadioButton19");
        jPanel8.add(jRadioButton19);

        jPanel2.add(jPanel8);

        jPanel9.setLayout(new java.awt.GridLayout(9, 0));

        jLabel16.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabel16.setText("jLabel16");
        jPanel9.add(jLabel16);

        jLabel17.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel17.setText("jLabel17");
        jPanel9.add(jLabel17);

        jLabel18.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabel18.setText("jLabel18");
        jPanel9.add(jLabel18);

        jRadioButton20.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jRadioButton20.setText("jRadioButton20");
        jPanel9.add(jRadioButton20);

        jRadioButton21.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jRadioButton21.setText("jRadioButton21");
        jPanel9.add(jRadioButton21);

        jRadioButton22.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jRadioButton22.setText("jRadioButton22");
        jPanel9.add(jRadioButton22);

        jRadioButton23.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jRadioButton23.setText("jRadioButton23");
        jPanel9.add(jRadioButton23);

        jRadioButton24.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jRadioButton24.setText("jRadioButton24");
        jPanel9.add(jRadioButton24);

        jPanel2.add(jPanel9);

        jPanel7.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 900, 1540));

        jScrollPane1.setViewportView(jPanel7);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 1020, 760));

        jButton1.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(253, 116, 1));
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 860, 140, 40));

        jButton2.setBackground(new java.awt.Color(253, 116, 1));
        jButton2.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Finalizar");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 855, 140, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 950));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PracticarResolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PracticarResolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PracticarResolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PracticarResolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatLightLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PracticarResolucion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
