/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import com.formdev.flatlaf.FlatLightLaf;

/**
 *
 * @author Usuario
 */
public class PracticaSolucionario extends javax.swing.JFrame {

    /**
     * Creates new form PracticarResolucion
     */
    public PracticaSolucionario() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanelBgSolucionario = new javax.swing.JPanel();
        jLabelBCSolucionario = new javax.swing.JLabel();
        jScrollPaneSolucionario = new javax.swing.JScrollPane();
        jPanelContenedorTxtRespuestas = new javax.swing.JPanel();
        jLabelIDSolucionario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelContenedorTexto = new javax.swing.JPanel();
        jLabelTextoSolucionario = new javax.swing.JLabel();
        jPanelContenedorRespuestas = new javax.swing.JPanel();
        jPanelRespuesta1 = new javax.swing.JPanel();
        jLabelTituloPregunta = new javax.swing.JLabel();
        jLabelEnunciado = new javax.swing.JLabel();
        jLabelTituloAlternativaCorrecta = new javax.swing.JLabel();
        jLabelAlternativaCorrecta = new javax.swing.JLabel();
        jLabelTituloRazonamiento = new javax.swing.JLabel();
        jPanelRazonamiento = new javax.swing.JPanel();
        jScrollPaneRazonamiento = new javax.swing.JScrollPane();
        jTextAreaRazonamiento = new javax.swing.JTextArea();
        jLabelRespuesta = new javax.swing.JLabel();
        jPanelRespuesta2 = new javax.swing.JPanel();
        jLabelTituloPregunta2 = new javax.swing.JLabel();
        jLabelEnunciado2 = new javax.swing.JLabel();
        jLabelTituloAlternativaCorrecta2 = new javax.swing.JLabel();
        jLabelAlternativaCorrecta2 = new javax.swing.JLabel();
        jLabelTituloRazonamiento2 = new javax.swing.JLabel();
        jPanelRazonamiento2 = new javax.swing.JPanel();
        jScrollPaneRazonamiento2 = new javax.swing.JScrollPane();
        jTextAreaRazonamiento2 = new javax.swing.JTextArea();
        jLabelRespuesta2 = new javax.swing.JLabel();
        jPanelRespuesta3 = new javax.swing.JPanel();
        jLabelTituloPregunta3 = new javax.swing.JLabel();
        jLabelEnunciado3 = new javax.swing.JLabel();
        jLabelTituloAlternativaCorrecta3 = new javax.swing.JLabel();
        jLabelAlternativaCorrecta3 = new javax.swing.JLabel();
        jLabelTituloRazonamiento3 = new javax.swing.JLabel();
        jPanelRazonamiento3 = new javax.swing.JPanel();
        jScrollPaneRazonamiento3 = new javax.swing.JScrollPane();
        jTextAreaRazonamiento3 = new javax.swing.JTextArea();
        jLabelRespuesta3 = new javax.swing.JLabel();
        btnVerReporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelBgSolucionario.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBgSolucionario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelBCSolucionario.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabelBCSolucionario.setText("Juez Cachimbo / Practicar / Solucionario");
        jPanelBgSolucionario.add(jLabelBCSolucionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jScrollPaneSolucionario.setColumnHeaderView(null);

        jPanelContenedorTxtRespuestas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelIDSolucionario.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabelIDSolucionario.setText("ID: {id_texto}");
        jPanelContenedorTxtRespuestas.add(jLabelIDSolucionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));
        jPanelContenedorTxtRespuestas.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 870, -1));

        jPanelContenedorTexto.setLayout(new java.awt.GridLayout(1, 0));

        jLabelTextoSolucionario.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabelTextoSolucionario.setText("<html><p>knbrebvubervubpievbibiwvebibpeiwvbibbwib2yievbypbwylkbypwveolqhvwvdhfvjlvlasaljevouvaeLorem ipsum dolor sit amet consectetur adipisicing elit. Fuga fugiat dolorem voluptatem architecto nulla dicta, distinctio natus accusamus sit temporibus et error tempore voluptates in optio quasi sequi? Eaque accusantium maiores eum modi reprehenderit voluptates praesentium tenetur vero? Et officia assumenda culpa, quos eaque magnam dolores facere eum quod nemo, neque, quisquam obcaecati asperiores ad dignissimos reprehenderit quaerat eligendi tempore. Doloremque deserunt distinctio qui hic ipsum, eius nulla iusto dolorem laborum molestias, saepe eveniet odio, fuga officia! Maiores corrupti animi quas officiis alias reiciendis pariatur quibusdam eos iure sit. Debitis unde, porro dicta provident blanditiis ea laudantium quasi sed, quam autem numquam cumque deserunt iure ipsa minima nihil suscipit, temporibus alias ad aperiam? kjryiqvveaiuucgnqob73qct4bjehdcwisivsdibibdskwebviunuwweipuvweubevubevefvbuoevuibeuibvefuiebvbdkjnajkñdnjkfdibeivew Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga fugiat dolorem voluptatem architecto nulla dicta, distinctio natus accusamus sit temporibus et error tempore voluptates in optio quasi sequi? Eaque accusantium maiores eum modi reprehenderit voluptates praesentium tenetur vero? Et officia assumenda culpa, quos eaque magnam dolores facere eum quod nemo, neque, quisquam obcaecati asperiores ad dignissimos reprehenderit quaerat eligendi tempore. Doloremque deserunt distinctio qui hic ipsum, eius nulla iusto dolorem laborum molestias, saepe eveniet odio, fuga officia! Maiores corrupti animi quas officiis alias reiciendis pariatur quibusdam eos iure sit. Debitis unde, porro dicta provident blanditiis ea laudantium quasi sed, quam autem numquam cumque deserunt iure ipsa minima nihil suscipit, temporibus alias ad aperiam? </p></html>");
        jLabelTextoSolucionario.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelTextoSolucionario.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanelContenedorTexto.add(jLabelTextoSolucionario);

        jPanelContenedorTxtRespuestas.add(jPanelContenedorTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 880, 470));

        jPanelContenedorRespuestas.setLayout(new javax.swing.BoxLayout(jPanelContenedorRespuestas, javax.swing.BoxLayout.PAGE_AXIS));

        jPanelRespuesta1.setLayout(new java.awt.GridLayout(8, 0));

        jLabelTituloPregunta.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabelTituloPregunta.setText("Pregunta 01");
        jPanelRespuesta1.add(jLabelTituloPregunta);

        jLabelEnunciado.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabelEnunciado.setText("Enunciado");
        jPanelRespuesta1.add(jLabelEnunciado);

        jLabelTituloAlternativaCorrecta.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabelTituloAlternativaCorrecta.setText("Alternativa correcta");
        jPanelRespuesta1.add(jLabelTituloAlternativaCorrecta);

        jLabelAlternativaCorrecta.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabelAlternativaCorrecta.setText("Alternativa E");
        jPanelRespuesta1.add(jLabelAlternativaCorrecta);

        jLabelTituloRazonamiento.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabelTituloRazonamiento.setText("Razonamiento");
        jPanelRespuesta1.add(jLabelTituloRazonamiento);

        jPanelRazonamiento.setLayout(new javax.swing.BoxLayout(jPanelRazonamiento, javax.swing.BoxLayout.LINE_AXIS));

        jTextAreaRazonamiento.setEditable(false);
        jTextAreaRazonamiento.setColumns(20);
        jTextAreaRazonamiento.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jTextAreaRazonamiento.setLineWrap(true);
        jTextAreaRazonamiento.setRows(8);
        jTextAreaRazonamiento.setTabSize(10);
        jTextAreaRazonamiento.setText("Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo voluptatem obcaecati in porro suscipit, dolores omnis voluptates quasi quisquam?.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo voluptatem obcaecati in porro suscipit, dolores omnis voluptates quasi quisquam?.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo voluptatem obcaecati in porro suscipit, dolores omnis voluptates quasi quisquam?.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo voluptatem obcaecati in porro suscipit, dolores omnis voluptates quasi quisquam?.");
        jTextAreaRazonamiento.setWrapStyleWord(true);
        jTextAreaRazonamiento.setFocusable(false);
        jScrollPaneRazonamiento.setViewportView(jTextAreaRazonamiento);

        jPanelRazonamiento.add(jScrollPaneRazonamiento);

        jPanelRespuesta1.add(jPanelRazonamiento);

        jLabelRespuesta.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabelRespuesta.setForeground(new java.awt.Color(111, 114, 118));
        jLabelRespuesta.setText("Respuesta incorrecta");
        jPanelRespuesta1.add(jLabelRespuesta);

        jPanelContenedorRespuestas.add(jPanelRespuesta1);

        jPanelRespuesta2.setLayout(new java.awt.GridLayout(9, 0));

        jLabelTituloPregunta2.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabelTituloPregunta2.setText("Pregunta 02");
        jPanelRespuesta2.add(jLabelTituloPregunta2);

        jLabelEnunciado2.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabelEnunciado2.setText("Enunciado");
        jPanelRespuesta2.add(jLabelEnunciado2);

        jLabelTituloAlternativaCorrecta2.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabelTituloAlternativaCorrecta2.setText("Alternativa correcta");
        jPanelRespuesta2.add(jLabelTituloAlternativaCorrecta2);

        jLabelAlternativaCorrecta2.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabelAlternativaCorrecta2.setText("Alternativa C");
        jPanelRespuesta2.add(jLabelAlternativaCorrecta2);

        jLabelTituloRazonamiento2.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabelTituloRazonamiento2.setText("Razonamiento");
        jPanelRespuesta2.add(jLabelTituloRazonamiento2);

        jPanelRazonamiento2.setLayout(new javax.swing.BoxLayout(jPanelRazonamiento2, javax.swing.BoxLayout.LINE_AXIS));

        jTextAreaRazonamiento2.setEditable(false);
        jTextAreaRazonamiento2.setColumns(20);
        jTextAreaRazonamiento2.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jTextAreaRazonamiento2.setLineWrap(true);
        jTextAreaRazonamiento2.setRows(5);
        jTextAreaRazonamiento2.setText("Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo voluptatem obcaecati in porro suscipit, dolores omnis voluptates quasi quisquam?.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo voluptatem obcaecati in porro suscipit, dolores omnis voluptates quasi quisquam?.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo voluptatem obcaecati in porro suscipit, dolores omnis voluptates quasi quisquam?.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo voluptatem obcaecati in porro suscipit, dolores omnis voluptates quasi quisquam?.");
        jTextAreaRazonamiento2.setWrapStyleWord(true);
        jScrollPaneRazonamiento2.setViewportView(jTextAreaRazonamiento2);

        jPanelRazonamiento2.add(jScrollPaneRazonamiento2);

        jPanelRespuesta2.add(jPanelRazonamiento2);

        jLabelRespuesta2.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabelRespuesta2.setForeground(new java.awt.Color(251, 132, 33));
        jLabelRespuesta2.setText("Respuesta correcta");
        jPanelRespuesta2.add(jLabelRespuesta2);

        jPanelContenedorRespuestas.add(jPanelRespuesta2);

        jPanelRespuesta3.setLayout(new java.awt.GridLayout(9, 0));

        jLabelTituloPregunta3.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabelTituloPregunta3.setText("Pregunta 03");
        jPanelRespuesta3.add(jLabelTituloPregunta3);

        jLabelEnunciado3.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabelEnunciado3.setText("Enunciado");
        jPanelRespuesta3.add(jLabelEnunciado3);

        jLabelTituloAlternativaCorrecta3.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabelTituloAlternativaCorrecta3.setText("Alternativa correcta");
        jPanelRespuesta3.add(jLabelTituloAlternativaCorrecta3);

        jLabelAlternativaCorrecta3.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabelAlternativaCorrecta3.setText("Alternativa D");
        jPanelRespuesta3.add(jLabelAlternativaCorrecta3);

        jLabelTituloRazonamiento3.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabelTituloRazonamiento3.setText("Razonamiento");
        jPanelRespuesta3.add(jLabelTituloRazonamiento3);

        jPanelRazonamiento3.setLayout(new javax.swing.BoxLayout(jPanelRazonamiento3, javax.swing.BoxLayout.LINE_AXIS));

        jTextAreaRazonamiento3.setEditable(false);
        jTextAreaRazonamiento3.setColumns(20);
        jTextAreaRazonamiento3.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jTextAreaRazonamiento3.setLineWrap(true);
        jTextAreaRazonamiento3.setRows(5);
        jTextAreaRazonamiento3.setText("FB8421Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo voluptatem obcaecati in porro suscipit, dolores omnis voluptates quasi quisquam?.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo voluptatem obcaecati in porro suscipit, dolores omnis voluptates quasi quisquam?.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo voluptatem obcaecati in porro suscipit, dolores omnis voluptates quasi quisquam?.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo voluptatem obcaecati in porro suscipit, dolores omnis voluptates quasi quisquam?.");
        jTextAreaRazonamiento3.setWrapStyleWord(true);
        jScrollPaneRazonamiento3.setViewportView(jTextAreaRazonamiento3);

        jPanelRazonamiento3.add(jScrollPaneRazonamiento3);

        jPanelRespuesta3.add(jPanelRazonamiento3);

        jLabelRespuesta3.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabelRespuesta3.setForeground(new java.awt.Color(111, 114, 118));
        jLabelRespuesta3.setText("Respuesta incorrecta");
        jPanelRespuesta3.add(jLabelRespuesta3);

        jPanelContenedorRespuestas.add(jPanelRespuesta3);

        jPanelContenedorTxtRespuestas.add(jPanelContenedorRespuestas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, 900, 1470));

        jScrollPaneSolucionario.setViewportView(jPanelContenedorTxtRespuestas);

        jPanelBgSolucionario.add(jScrollPaneSolucionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 1020, 760));

        btnVerReporte.setBackground(new java.awt.Color(253, 116, 1));
        btnVerReporte.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        btnVerReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnVerReporte.setText("Finalizar");
        jPanelBgSolucionario.add(btnVerReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 870, 170, 40));

        getContentPane().add(jPanelBgSolucionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 950));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PracticaSolucionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PracticaSolucionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PracticaSolucionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PracticaSolucionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatLightLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PracticaSolucionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerReporte;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabelAlternativaCorrecta;
    private javax.swing.JLabel jLabelAlternativaCorrecta2;
    private javax.swing.JLabel jLabelAlternativaCorrecta3;
    private javax.swing.JLabel jLabelBCSolucionario;
    private javax.swing.JLabel jLabelEnunciado;
    private javax.swing.JLabel jLabelEnunciado2;
    private javax.swing.JLabel jLabelEnunciado3;
    private javax.swing.JLabel jLabelIDSolucionario;
    private javax.swing.JLabel jLabelRespuesta;
    private javax.swing.JLabel jLabelRespuesta2;
    private javax.swing.JLabel jLabelRespuesta3;
    private javax.swing.JLabel jLabelTextoSolucionario;
    private javax.swing.JLabel jLabelTituloAlternativaCorrecta;
    private javax.swing.JLabel jLabelTituloAlternativaCorrecta2;
    private javax.swing.JLabel jLabelTituloAlternativaCorrecta3;
    private javax.swing.JLabel jLabelTituloPregunta;
    private javax.swing.JLabel jLabelTituloPregunta2;
    private javax.swing.JLabel jLabelTituloPregunta3;
    private javax.swing.JLabel jLabelTituloRazonamiento;
    private javax.swing.JLabel jLabelTituloRazonamiento2;
    private javax.swing.JLabel jLabelTituloRazonamiento3;
    private javax.swing.JPanel jPanelBgSolucionario;
    private javax.swing.JPanel jPanelContenedorRespuestas;
    private javax.swing.JPanel jPanelContenedorTexto;
    private javax.swing.JPanel jPanelContenedorTxtRespuestas;
    private javax.swing.JPanel jPanelRazonamiento;
    private javax.swing.JPanel jPanelRazonamiento2;
    private javax.swing.JPanel jPanelRazonamiento3;
    private javax.swing.JPanel jPanelRespuesta1;
    private javax.swing.JPanel jPanelRespuesta2;
    private javax.swing.JPanel jPanelRespuesta3;
    private javax.swing.JScrollPane jScrollPaneRazonamiento;
    private javax.swing.JScrollPane jScrollPaneRazonamiento2;
    private javax.swing.JScrollPane jScrollPaneRazonamiento3;
    private javax.swing.JScrollPane jScrollPaneSolucionario;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextAreaRazonamiento;
    private javax.swing.JTextArea jTextAreaRazonamiento2;
    private javax.swing.JTextArea jTextAreaRazonamiento3;
    // End of variables declaration//GEN-END:variables
}
