/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import com.formdev.flatlaf.FlatLightLaf;

/**
 *
 * @author Usuario
 */
public class PracticarResolucion extends javax.swing.JFrame {

    /**
     * Creates new form PracticarResolucion
     */
    public PracticarResolucion() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtnGrupo1 = new javax.swing.ButtonGroup();
        rbtnGrupo2 = new javax.swing.ButtonGroup();
        bgPracticarResolucion = new javax.swing.JPanel();
        jLabelBCPracticarRe = new javax.swing.JLabel();
        jScrollPaneResolucion = new javax.swing.JScrollPane();
        jPanelTxtPreguntas = new javax.swing.JPanel();
        jLabelIDTxt = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelContenedorTexto = new javax.swing.JPanel();
        jLabelTextoEstudiante = new javax.swing.JLabel();
        jPanelContenedorPreguntas = new javax.swing.JPanel();
        jPanelPregunta = new javax.swing.JPanel();
        jLabelNumPregunta = new javax.swing.JLabel();
        jLabelEnunciado = new javax.swing.JLabel();
        jLabelAlternativas = new javax.swing.JLabel();
        rbtnAlternativaA = new javax.swing.JRadioButton();
        rbtnAlternativaB = new javax.swing.JRadioButton();
        rbtnAlternativaC = new javax.swing.JRadioButton();
        rbtnAlternativaD = new javax.swing.JRadioButton();
        rbtnAlternativaE = new javax.swing.JRadioButton();
        jPanelPregunta2 = new javax.swing.JPanel();
        jLabelNumPregunta2 = new javax.swing.JLabel();
        jLabelEnunciado2 = new javax.swing.JLabel();
        jLabelAlternativas2 = new javax.swing.JLabel();
        rbtnAlternativaA2 = new javax.swing.JRadioButton();
        rbtnAlternativaB2 = new javax.swing.JRadioButton();
        rbtnAlternativaC2 = new javax.swing.JRadioButton();
        rbtnAlternativaD2 = new javax.swing.JRadioButton();
        rbtnAlternativaE2 = new javax.swing.JRadioButton();
        btnCancelar = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgPracticarResolucion.setBackground(new java.awt.Color(255, 255, 255));
        bgPracticarResolucion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelBCPracticarRe.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabelBCPracticarRe.setText("Juez Cachimbo / Practicar / Resolución");
        bgPracticarResolucion.add(jLabelBCPracticarRe, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jScrollPaneResolucion.setColumnHeaderView(null);

        jPanelTxtPreguntas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelIDTxt.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabelIDTxt.setText("ID: {id_texto}");
        jPanelTxtPreguntas.add(jLabelIDTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));
        jPanelTxtPreguntas.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 870, -1));

        jPanelContenedorTexto.setLayout(new java.awt.GridLayout(1, 0));

        jLabelTextoEstudiante.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabelTextoEstudiante.setText("<html><p>knbrebvubervubpievbibiwvebibpeiwvbibbwib2yievbypbwylkbypwveolqhvwvdhfvjlvlasaljevouvaeLorem ipsum dolor sit amet consectetur adipisicing elit. Fuga fugiat dolorem voluptatem architecto nulla dicta, distinctio natus accusamus sit temporibus et error tempore voluptates in optio quasi sequi? Eaque accusantium maiores eum modi reprehenderit voluptates praesentium tenetur vero? Et officia assumenda culpa, quos eaque magnam dolores facere eum quod nemo, neque, quisquam obcaecati asperiores ad dignissimos reprehenderit quaerat eligendi tempore. Doloremque deserunt distinctio qui hic ipsum, eius nulla iusto dolorem laborum molestias, saepe eveniet odio, fuga officia! Maiores corrupti animi quas officiis alias reiciendis pariatur quibusdam eos iure sit. Debitis unde, porro dicta provident blanditiis ea laudantium quasi sed, quam autem numquam cumque deserunt iure ipsa minima nihil suscipit, temporibus alias ad aperiam? kjryiqvveaiuucgnqob73qct4bjehdcwisivsdibibdskwebviunuwweipuvweubevubevefvbuoevuibeuibvefuiebvbdkjnajkñdnjkfdibeivew Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga fugiat dolorem voluptatem architecto nulla dicta, distinctio natus accusamus sit temporibus et error tempore voluptates in optio quasi sequi? Eaque accusantium maiores eum modi reprehenderit voluptates praesentium tenetur vero? Et officia assumenda culpa, quos eaque magnam dolores facere eum quod nemo, neque, quisquam obcaecati asperiores ad dignissimos reprehenderit quaerat eligendi tempore. Doloremque deserunt distinctio qui hic ipsum, eius nulla iusto dolorem laborum molestias, saepe eveniet odio, fuga officia! Maiores corrupti animi quas officiis alias reiciendis pariatur quibusdam eos iure sit. Debitis unde, porro dicta provident blanditiis ea laudantium quasi sed, quam autem numquam cumque deserunt iure ipsa minima nihil suscipit, temporibus alias ad aperiam? </p></html>");
        jLabelTextoEstudiante.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelTextoEstudiante.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanelContenedorTexto.add(jLabelTextoEstudiante);

        jPanelTxtPreguntas.add(jPanelContenedorTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 880, 490));

        jPanelContenedorPreguntas.setLayout(new javax.swing.BoxLayout(jPanelContenedorPreguntas, javax.swing.BoxLayout.PAGE_AXIS));

        jPanelPregunta.setLayout(new java.awt.GridLayout(9, 0));

        jLabelNumPregunta.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabelNumPregunta.setText("Pregunta 01");
        jPanelPregunta.add(jLabelNumPregunta);

        jLabelEnunciado.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabelEnunciado.setText("Enunciado");
        jPanelPregunta.add(jLabelEnunciado);

        jLabelAlternativas.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabelAlternativas.setText("Alternativas");
        jPanelPregunta.add(jLabelAlternativas);

        rbtnGrupo1.add(rbtnAlternativaA);
        rbtnAlternativaA.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        rbtnAlternativaA.setText("A) Alternativa 1");
        jPanelPregunta.add(rbtnAlternativaA);

        rbtnGrupo1.add(rbtnAlternativaB);
        rbtnAlternativaB.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        rbtnAlternativaB.setText("B) Alternativa 2");
        jPanelPregunta.add(rbtnAlternativaB);

        rbtnGrupo1.add(rbtnAlternativaC);
        rbtnAlternativaC.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        rbtnAlternativaC.setText("C) Alternativa 3");
        jPanelPregunta.add(rbtnAlternativaC);

        rbtnGrupo1.add(rbtnAlternativaD);
        rbtnAlternativaD.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        rbtnAlternativaD.setText("D) Alternativa 4");
        jPanelPregunta.add(rbtnAlternativaD);

        rbtnGrupo1.add(rbtnAlternativaE);
        rbtnAlternativaE.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        rbtnAlternativaE.setText("E) Alternativa 5");
        jPanelPregunta.add(rbtnAlternativaE);

        jPanelContenedorPreguntas.add(jPanelPregunta);

        jPanelPregunta2.setLayout(new java.awt.GridLayout(9, 0));

        jLabelNumPregunta2.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabelNumPregunta2.setText("Pregunta 02");
        jPanelPregunta2.add(jLabelNumPregunta2);

        jLabelEnunciado2.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabelEnunciado2.setText("Enunciado");
        jPanelPregunta2.add(jLabelEnunciado2);

        jLabelAlternativas2.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabelAlternativas2.setText("Alternativas");
        jPanelPregunta2.add(jLabelAlternativas2);

        rbtnGrupo2.add(rbtnAlternativaA2);
        rbtnAlternativaA2.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        rbtnAlternativaA2.setText("A) Alternativa 1");
        jPanelPregunta2.add(rbtnAlternativaA2);

        rbtnGrupo2.add(rbtnAlternativaB2);
        rbtnAlternativaB2.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        rbtnAlternativaB2.setText("B) Alternativa 2");
        jPanelPregunta2.add(rbtnAlternativaB2);

        rbtnGrupo2.add(rbtnAlternativaC2);
        rbtnAlternativaC2.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        rbtnAlternativaC2.setText("C) Alternativa 3");
        jPanelPregunta2.add(rbtnAlternativaC2);

        rbtnGrupo2.add(rbtnAlternativaD2);
        rbtnAlternativaD2.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        rbtnAlternativaD2.setText("D) Alternativa 4");
        jPanelPregunta2.add(rbtnAlternativaD2);

        rbtnGrupo2.add(rbtnAlternativaE2);
        rbtnAlternativaE2.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        rbtnAlternativaE2.setText("E) Alternativa 5");
        jPanelPregunta2.add(rbtnAlternativaE2);

        jPanelContenedorPreguntas.add(jPanelPregunta2);

        jPanelTxtPreguntas.add(jPanelContenedorPreguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 900, 1540));

        jScrollPaneResolucion.setViewportView(jPanelTxtPreguntas);

        bgPracticarResolucion.add(jScrollPaneResolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 1020, 760));

        btnCancelar.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(253, 116, 1));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        bgPracticarResolucion.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 860, 140, 40));

        btnFinalizar.setBackground(new java.awt.Color(253, 116, 1));
        btnFinalizar.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        btnFinalizar.setForeground(new java.awt.Color(255, 255, 255));
        btnFinalizar.setText("Finalizar");
        bgPracticarResolucion.add(btnFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 855, 140, 40));

        getContentPane().add(bgPracticarResolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 950));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PracticarResolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PracticarResolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PracticarResolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PracticarResolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatLightLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PracticarResolucion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPracticarResolucion;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JLabel jLabelAlternativas;
    private javax.swing.JLabel jLabelAlternativas2;
    private javax.swing.JLabel jLabelBCPracticarRe;
    private javax.swing.JLabel jLabelEnunciado;
    private javax.swing.JLabel jLabelEnunciado2;
    private javax.swing.JLabel jLabelIDTxt;
    private javax.swing.JLabel jLabelNumPregunta;
    private javax.swing.JLabel jLabelNumPregunta2;
    private javax.swing.JLabel jLabelTextoEstudiante;
    private javax.swing.JPanel jPanelContenedorPreguntas;
    private javax.swing.JPanel jPanelContenedorTexto;
    private javax.swing.JPanel jPanelPregunta;
    private javax.swing.JPanel jPanelPregunta2;
    private javax.swing.JPanel jPanelTxtPreguntas;
    private javax.swing.JScrollPane jScrollPaneResolucion;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbtnAlternativaA;
    private javax.swing.JRadioButton rbtnAlternativaA2;
    private javax.swing.JRadioButton rbtnAlternativaB;
    private javax.swing.JRadioButton rbtnAlternativaB2;
    private javax.swing.JRadioButton rbtnAlternativaC;
    private javax.swing.JRadioButton rbtnAlternativaC2;
    private javax.swing.JRadioButton rbtnAlternativaD;
    private javax.swing.JRadioButton rbtnAlternativaD2;
    private javax.swing.JRadioButton rbtnAlternativaE;
    private javax.swing.JRadioButton rbtnAlternativaE2;
    private javax.swing.ButtonGroup rbtnGrupo1;
    private javax.swing.ButtonGroup rbtnGrupo2;
    // End of variables declaration//GEN-END:variables
}
