
package views;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.BorderLayout;
import javax.swing.JPanel;


/**
 *
 * @author Vilberto Patricio
 */

public class RegisterDocente1 extends javax.swing.JFrame {

    /**
     * Creates new form PanelRegister
     */
    public RegisterDocente1() {
        initComponents();
        setTitle("Juez Cachimbo");
        setResizable(false);
    }
    
    public void showJPanel(JPanel p){
        p.setSize(1260, 850);
        p.setLocation(0, 0);
        
        PanelDE.removeAll();
        PanelDE.add(p, BorderLayout.CENTER);
        PanelDE.revalidate();
        PanelDE.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDE = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        registrarse = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jTFApellidos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTFDias = new javax.swing.JTextField();
        jTFMeses = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTFAnio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTFCarreraProfesional = new javax.swing.JTextField();
        btnSiguiente = new javax.swing.JButton();
        Panelimg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1650, 953));

        PanelDE.setBackground(new java.awt.Color(255, 255, 255));
        PanelDE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        PanelDE.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 100, 100));

        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Juez_cachimbp.png"))); // NOI18N
        PanelDE.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 210, 100));

        registrarse.setFont(new java.awt.Font("Poppins SemiBold", 1, 20)); // NOI18N
        registrarse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrarse.setText("Docente");
        PanelDE.add(registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 210, -1));

        jTFNombre.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jTFNombre.setForeground(new java.awt.Color(85, 85, 85));
        PanelDE.add(jTFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 410, 40));

        jTFApellidos.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jTFApellidos.setForeground(new java.awt.Color(85, 85, 85));
        PanelDE.add(jTFApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 410, 40));

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(85, 85, 85));
        jLabel2.setText("Apellidos");
        PanelDE.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(85, 85, 85));
        jLabel3.setText("Nombre");
        PanelDE.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(85, 85, 85));
        jLabel4.setText("Fecha de nacimiento");
        PanelDE.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, -1, -1));

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(85, 85, 85));
        jLabel5.setText("Dia");
        PanelDE.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, -1, -1));

        jTFDias.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        jTFDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDiasActionPerformed(evt);
            }
        });
        PanelDE.add(jTFDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, -1, 30));

        jTFMeses.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        PanelDE.add(jTFMeses, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, 140, 30));

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(85, 85, 85));
        jLabel7.setText("Numero del mes");
        PanelDE.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, 140, -1));

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(85, 85, 85));
        jLabel8.setText("Año");
        PanelDE.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, -1, -1));

        jTFAnio.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        PanelDE.add(jTFAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 560, -1, 30));

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(85, 85, 85));
        jLabel6.setText("Carrera profesional");
        PanelDE.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 630, -1, -1));

        jTFCarreraProfesional.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jTFCarreraProfesional.setForeground(new java.awt.Color(85, 85, 85));
        PanelDE.add(jTFCarreraProfesional, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 670, 410, 40));

        btnSiguiente.setBackground(new java.awt.Color(253, 116, 1));
        btnSiguiente.setFont(new java.awt.Font("Poppins SemiBold", 0, 20)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguiente.setText("Siguiente");
        btnSiguiente.setFocusable(false);
        PanelDE.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 770, 410, 50));

        Panelimg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/password.png"))); // NOI18N
        Panelimg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 94, 850, 780));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelDE, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Panelimg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDE, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)
            .addComponent(Panelimg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTFDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDiasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterDocente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterDocente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterDocente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterDocente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        FlatLightLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterDocente1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDE;
    private javax.swing.JPanel Panelimg;
    public javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTFAnio;
    private javax.swing.JTextField jTFApellidos;
    private javax.swing.JTextField jTFCarreraProfesional;
    private javax.swing.JTextField jTFDias;
    private javax.swing.JTextField jTFMeses;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JLabel registrarse;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
