
package views;

import com.formdev.flatlaf.FlatLightLaf;


public class RegisterDocente1 extends javax.swing.JPanel {

    /**
     * Creates new form RegisterDocente1
     */
    public RegisterDocente1() {
        initComponents();
        FlatLightLaf.setup(); //Modifica el diseño de los componentes de las interfaces graficas
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgRegisterDC1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFApellidos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTFCarreraProfesional = new javax.swing.JTextField();
        btnSiguiente = new javax.swing.JButton();
        jTFDias = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFMeses = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTFAnio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(658, 953));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgRegisterDC1.setBackground(new java.awt.Color(255, 255, 255));
        bgRegisterDC1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Juez_cachimbp.png"))); // NOI18N
        bgRegisterDC1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 210, 100));

        icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        bgRegisterDC1.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 100, 100));

        jLabel6.setFont(new java.awt.Font("Poppins SemiBold", 1, 22)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Docente");
        bgRegisterDC1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 130, -1));

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(85, 85, 85));
        jLabel1.setText("Nombre");
        bgRegisterDC1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        jTFNombre.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jTFNombre.setForeground(new java.awt.Color(85, 85, 85));
        bgRegisterDC1.add(jTFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 410, 40));

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(85, 85, 85));
        jLabel2.setText("Apellidos");
        bgRegisterDC1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        jTFApellidos.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jTFApellidos.setForeground(new java.awt.Color(85, 85, 85));
        bgRegisterDC1.add(jTFApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 410, 40));

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(85, 85, 85));
        jLabel3.setText("Fecha de nacimiento");
        bgRegisterDC1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, -1));

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(85, 85, 85));
        jLabel4.setText("Carrera profesional");
        bgRegisterDC1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 600, -1, -1));

        jTFCarreraProfesional.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jTFCarreraProfesional.setForeground(new java.awt.Color(85, 85, 85));
        bgRegisterDC1.add(jTFCarreraProfesional, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 640, 410, 40));

        btnSiguiente.setBackground(new java.awt.Color(253, 116, 1));
        btnSiguiente.setFont(new java.awt.Font("Poppins SemiBold", 0, 20)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguiente.setText("Siguiente");
        btnSiguiente.setFocusable(false);
        bgRegisterDC1.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 790, 410, 50));

        jTFDias.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        jTFDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDiasActionPerformed(evt);
            }
        });
        bgRegisterDC1.add(jTFDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, -1, 30));

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(85, 85, 85));
        jLabel5.setText("Dia");
        bgRegisterDC1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, -1, -1));

        jTFMeses.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        bgRegisterDC1.add(jTFMeses, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, 140, 30));

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(85, 85, 85));
        jLabel7.setText("Numero del mes");
        bgRegisterDC1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, 140, -1));

        jTFAnio.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        bgRegisterDC1.add(jTFAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, -1, 30));

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(85, 85, 85));
        jLabel8.setText("Año");
        bgRegisterDC1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, -1, -1));

        add(bgRegisterDC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 658, 953));
    }// </editor-fold>//GEN-END:initComponents

    private void jTFDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDiasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgRegisterDC1;
    public javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTFAnio;
    private javax.swing.JTextField jTFApellidos;
    private javax.swing.JTextField jTFCarreraProfesional;
    private javax.swing.JTextField jTFDias;
    private javax.swing.JTextField jTFMeses;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
