
package views;

import com.formdev.flatlaf.FlatLightLaf;


/**
 *
 * @author Vilberto Patricio
 */

public class RegisterDocente1 extends javax.swing.JFrame {

    /**
     * Creates new form PanelRegister
     */
    public RegisterDocente1() {
        initComponents();
        setTitle("Juez Cachimbo");
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDE = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        labelDocente = new javax.swing.JLabel();
        txtNombreRegisterDocente = new javax.swing.JTextField();
        txtApellidosRegisterD = new javax.swing.JTextField();
        jLabelApellidosRD = new javax.swing.JLabel();
        jLabelNombreRD = new javax.swing.JLabel();
        jLabelFechaRD = new javax.swing.JLabel();
        jLabelDiaRD = new javax.swing.JLabel();
        txtDiaRegisterD = new javax.swing.JTextField();
        txtNumeroMesRegisterD = new javax.swing.JTextField();
        jLabelMesRD = new javax.swing.JLabel();
        jLabelAnioRD = new javax.swing.JLabel();
        txtAnioRegisterD = new javax.swing.JTextField();
        jLabelCarreraRD = new javax.swing.JLabel();
        txtCarreraProfesionalRegisterD = new javax.swing.JTextField();
        btnSiguienteRegisterD = new javax.swing.JButton();
        Panelimg = new javax.swing.JPanel();
        jLabelImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1650, 953));

        PanelDE.setBackground(new java.awt.Color(255, 255, 255));
        PanelDE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        PanelDE.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 100, 100));

        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Juez_cachimbp.png"))); // NOI18N
        PanelDE.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 210, 100));

        labelDocente.setFont(new java.awt.Font("Poppins SemiBold", 1, 20)); // NOI18N
        labelDocente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDocente.setText("Docente");
        PanelDE.add(labelDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 210, -1));

        txtNombreRegisterDocente.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtNombreRegisterDocente.setForeground(new java.awt.Color(85, 85, 85));
        PanelDE.add(txtNombreRegisterDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 410, 40));

        txtApellidosRegisterD.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtApellidosRegisterD.setForeground(new java.awt.Color(85, 85, 85));
        PanelDE.add(txtApellidosRegisterD, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 410, 40));

        jLabelApellidosRD.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        jLabelApellidosRD.setForeground(new java.awt.Color(85, 85, 85));
        jLabelApellidosRD.setText("Apellidos");
        PanelDE.add(jLabelApellidosRD, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        jLabelNombreRD.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        jLabelNombreRD.setForeground(new java.awt.Color(85, 85, 85));
        jLabelNombreRD.setText("Nombre");
        PanelDE.add(jLabelNombreRD, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        jLabelFechaRD.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        jLabelFechaRD.setForeground(new java.awt.Color(85, 85, 85));
        jLabelFechaRD.setText("Fecha de nacimiento");
        PanelDE.add(jLabelFechaRD, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, -1, -1));

        jLabelDiaRD.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabelDiaRD.setForeground(new java.awt.Color(85, 85, 85));
        jLabelDiaRD.setText("Dia");
        PanelDE.add(jLabelDiaRD, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, -1, -1));

        txtDiaRegisterD.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        txtDiaRegisterD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaRegisterDActionPerformed(evt);
            }
        });
        PanelDE.add(txtDiaRegisterD, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, -1, 30));

        txtNumeroMesRegisterD.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        PanelDE.add(txtNumeroMesRegisterD, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, 140, 30));

        jLabelMesRD.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabelMesRD.setForeground(new java.awt.Color(85, 85, 85));
        jLabelMesRD.setText("Numero del mes");
        PanelDE.add(jLabelMesRD, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, 140, -1));

        jLabelAnioRD.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabelAnioRD.setForeground(new java.awt.Color(85, 85, 85));
        jLabelAnioRD.setText("Año");
        PanelDE.add(jLabelAnioRD, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, -1, -1));

        txtAnioRegisterD.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        PanelDE.add(txtAnioRegisterD, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 560, -1, 30));

        jLabelCarreraRD.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        jLabelCarreraRD.setForeground(new java.awt.Color(85, 85, 85));
        jLabelCarreraRD.setText("Carrera profesional");
        PanelDE.add(jLabelCarreraRD, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 630, -1, -1));

        txtCarreraProfesionalRegisterD.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtCarreraProfesionalRegisterD.setForeground(new java.awt.Color(85, 85, 85));
        PanelDE.add(txtCarreraProfesionalRegisterD, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 670, 410, 40));

        btnSiguienteRegisterD.setBackground(new java.awt.Color(253, 116, 1));
        btnSiguienteRegisterD.setFont(new java.awt.Font("Poppins SemiBold", 0, 20)); // NOI18N
        btnSiguienteRegisterD.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguienteRegisterD.setText("Siguiente");
        btnSiguienteRegisterD.setFocusable(false);
        PanelDE.add(btnSiguienteRegisterD, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 770, 410, 50));

        Panelimg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/password.png"))); // NOI18N
        Panelimg.add(jLabelImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 94, 850, 780));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelDE, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Panelimg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDE, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)
            .addComponent(Panelimg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDiaRegisterDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaRegisterDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaRegisterDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterDocente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterDocente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterDocente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterDocente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        FlatLightLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterDocente1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDE;
    private javax.swing.JPanel Panelimg;
    public javax.swing.JButton btnSiguienteRegisterD;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel jLabelAnioRD;
    private javax.swing.JLabel jLabelApellidosRD;
    private javax.swing.JLabel jLabelCarreraRD;
    private javax.swing.JLabel jLabelDiaRD;
    private javax.swing.JLabel jLabelFechaRD;
    private javax.swing.JLabel jLabelImg;
    private javax.swing.JLabel jLabelMesRD;
    private javax.swing.JLabel jLabelNombreRD;
    private javax.swing.JLabel labelDocente;
    private javax.swing.JLabel title;
    public javax.swing.JTextField txtAnioRegisterD;
    public javax.swing.JTextField txtApellidosRegisterD;
    public javax.swing.JTextField txtCarreraProfesionalRegisterD;
    public javax.swing.JTextField txtDiaRegisterD;
    public javax.swing.JTextField txtNombreRegisterDocente;
    public javax.swing.JTextField txtNumeroMesRegisterD;
    // End of variables declaration//GEN-END:variables
}
