
package views;

import com.formdev.flatlaf.FlatLightLaf;


/**
 *
 * @author Vilberto Patricio
 */

public class SeguimientoDocente extends javax.swing.JPanel {

    public SeguimientoDocente() {
        initComponents();
        FlatLightLaf.setup(); //Modifica el diseño de los componentes de las interfaces graficas
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgInicioDocente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelBreadCrumbsSeguimientoD = new javax.swing.JLabel();
        jTabbedPaneSeguimiento = new javax.swing.JTabbedPane();
        jPanelVisionGeneralD = new javax.swing.JPanel();
        jLabelTituloGrafico = new javax.swing.JLabel();
        jScrollPaneDescripcion = new javax.swing.JScrollPane();
        jTextAreaDescripcionGrafico = new javax.swing.JTextArea();
        jLabelIndicaciones = new javax.swing.JLabel();
        jPanelLeyenda = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnRefrescarGrafico = new javax.swing.JButton();
        jPanelUsuariosD = new javax.swing.JPanel();
        jScrollPaneUsuarios = new javax.swing.JScrollPane();
        jTableUsuarios = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgInicioDocente.setBackground(new java.awt.Color(241, 243, 246));
        bgInicioDocente.setPreferredSize(new java.awt.Dimension(1260, 850));
        bgInicioDocente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(253, 116, 1));
        jLabel1.setText("Seguimiento de los estudiantes");
        bgInicioDocente.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabelBreadCrumbsSeguimientoD.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabelBreadCrumbsSeguimientoD.setText("Juez Cachimbo / Seguimiento");
        bgInicioDocente.add(jLabelBreadCrumbsSeguimientoD, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jTabbedPaneSeguimiento.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N

        jPanelVisionGeneralD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTituloGrafico.setFont(new java.awt.Font("Poppins SemiBold", 0, 22)); // NOI18N
        jLabelTituloGrafico.setText("Gráfico circular");
        jPanelVisionGeneralD.add(jLabelTituloGrafico, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        jScrollPaneDescripcion.setBorder(null);
        jScrollPaneDescripcion.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPaneDescripcion.setEnabled(false);
        jScrollPaneDescripcion.setFocusable(false);
        jScrollPaneDescripcion.setWheelScrollingEnabled(false);

        jTextAreaDescripcionGrafico.setEditable(false);
        jTextAreaDescripcionGrafico.setColumns(20);
        jTextAreaDescripcionGrafico.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jTextAreaDescripcionGrafico.setLineWrap(true);
        jTextAreaDescripcionGrafico.setRows(5);
        jTextAreaDescripcionGrafico.setText("El siguiente gráfico muestra la distribución circular de las preguntas correctas e incorrectas de un grupo de estudiantes. El gráfico circular es útil para representar una parte de un todo, en este caso, se representan las cantidades de preguntas correctas e incorrectas de un total de preguntas contestadas por un grupo de estudiantes.");
        jTextAreaDescripcionGrafico.setToolTipText("");
        jTextAreaDescripcionGrafico.setWrapStyleWord(true);
        jTextAreaDescripcionGrafico.setBorder(null);
        jTextAreaDescripcionGrafico.setFocusable(false);
        jScrollPaneDescripcion.setViewportView(jTextAreaDescripcionGrafico);

        jPanelVisionGeneralD.add(jScrollPaneDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 880, 110));

        jLabelIndicaciones.setText("Aquí va el gráfico circular - Usa el boton refrescar para poder generarlo");
        jPanelVisionGeneralD.add(jLabelIndicaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, -1));

        jPanelLeyenda.setBackground(new java.awt.Color(228, 229, 231));
        jPanelLeyenda.setFocusable(false);
        jPanelLeyenda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Poppins", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 39, 114));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Leyenda");
        jPanelLeyenda.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 150, -1));

        jPanel2.setBackground(new java.awt.Color(54, 123, 187));
        jPanelLeyenda.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 20, 20));

        jPanel3.setBackground(new java.awt.Color(244, 171, 73));
        jPanelLeyenda.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 20, 20));

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel5.setText("<html>Preguntas correctas</html>");
        jPanelLeyenda.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 120, -1));

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel6.setText("<html>Preguntas incorrectas</html>");
        jPanelLeyenda.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 130, 50));

        jPanelVisionGeneralD.add(jPanelLeyenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 210, 210, 260));

        btnRefrescarGrafico.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        btnRefrescarGrafico.setForeground(new java.awt.Color(30, 39, 114));
        btnRefrescarGrafico.setText("Refrescar gráfico");
        jPanelVisionGeneralD.add(btnRefrescarGrafico, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 510, 200, -1));

        jTabbedPaneSeguimiento.addTab("Visión general", jPanelVisionGeneralD);

        jPanelUsuariosD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableUsuarios.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jTableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Estudiante", "Textos leídos", "Preguntas correctas", "Preguntas incorrectas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneUsuarios.setViewportView(jTableUsuarios);

        jPanelUsuariosD.add(jScrollPaneUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 940, 470));

        jLabel2.setFont(new java.awt.Font("Poppins SemiBold", 0, 22)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Progreso de los estudiantes");
        jPanelUsuariosD.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 930, -1));

        jTabbedPaneSeguimiento.addTab("Estudiantes", jPanelUsuariosD);

        bgInicioDocente.add(jTabbedPaneSeguimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 1130, 690));

        jButton1.setBackground(new java.awt.Color(253, 116, 1));
        jButton1.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Crear ejercicio");
        bgInicioDocente.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 870, 190, 40));

        add(bgInicioDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 953));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgInicioDocente;
    private javax.swing.JButton btnRefrescarGrafico;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelBreadCrumbsSeguimientoD;
    private javax.swing.JLabel jLabelIndicaciones;
    private javax.swing.JLabel jLabelTituloGrafico;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelLeyenda;
    private javax.swing.JPanel jPanelUsuariosD;
    private javax.swing.JPanel jPanelVisionGeneralD;
    private javax.swing.JScrollPane jScrollPaneDescripcion;
    private javax.swing.JScrollPane jScrollPaneUsuarios;
    private javax.swing.JTabbedPane jTabbedPaneSeguimiento;
    public javax.swing.JTable jTableUsuarios;
    private javax.swing.JTextArea jTextAreaDescripcionGrafico;
    // End of variables declaration//GEN-END:variables
}
